/*
 * This file was automatically generated by EvoSuite
 * Fri Mar 13 23:55:17 GMT 2026
 */

package org.apache.commons.cli.help;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.ServiceLoader;
import java.util.Set;
import java.util.TreeSet;
import java.util.Vector;
import java.util.function.Function;
import org.apache.commons.cli.Option;
import org.apache.commons.cli.OptionGroup;
import org.apache.commons.cli.Options;
import org.apache.commons.cli.help.AbstractHelpFormatter;
import org.apache.commons.cli.help.HelpAppendable;
import org.apache.commons.cli.help.HelpFormatter;
import org.apache.commons.cli.help.OptionFormatter;
import org.apache.commons.cli.help.TableDefinition;
import org.apache.commons.cli.help.TextHelpAppendable;
import org.apache.commons.cli.help.TextStyle;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AbstractHelpFormatter_ESTest extends AbstractHelpFormatter_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder0);
      helpFormatter0.setSyntaxPrefix("Java version ");
      Options options0 = new Options();
      helpFormatter0.printHelp("Java version ", "Java version ", options0, (String) null, false);
      assertEquals("Java version ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      helpFormatter0.setSyntaxPrefix("@61~*yMG'`Wne>[e88k");
      Options options0 = new Options();
      helpFormatter0.printHelp("java.vm.version", "|%r(Nz0", options0, (String) null, true);
      assertEquals("@61~*yMG'`Wne>[e88k", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      Options options0 = new Options();
      Option option0 = new Option((String) null, " | ", false, "|c0gCn");
      options0.addOption(option0);
      helpFormatter0.sort(options0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      HashMap<Option, TextHelpAppendable> hashMap0 = new HashMap<Option, TextHelpAppendable>();
      Option option0 = new Option("optionFormatBuilder", "optionFormatBuilder", true, "usage: ");
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      hashMap0.put(option0, textHelpAppendable0);
      Set<Option> set0 = hashMap0.keySet();
      helpFormatter0.sort((Iterable<Option>) set0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      helpFormatter0.setSyntaxPrefix((String) null);
      String string0 = helpFormatter0.getSyntaxPrefix();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setOptionGroupSeparator((String) null);
      HelpFormatter helpFormatter0 = helpFormatter_Builder1.get();
      String string0 = helpFormatter0.getOptionGroupSeparator();
      assertEquals("", string0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder0);
      Option option0 = new Option((String) null, (String) null);
      helpFormatter0.getOptionFormatter(option0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      // Undeclared exception!
      try { 
        helpFormatter0.toSyntaxOptions((Options) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.AbstractHelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder0);
      // Undeclared exception!
      try { 
        helpFormatter0.toSyntaxOptions((OptionGroup) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.AbstractHelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder0);
      Option option0 = new Option((String) null, (String) null);
      Vector<Option> vector0 = new Vector<Option>();
      ArrayDeque<Option> arrayDeque0 = new ArrayDeque<Option>(vector0);
      arrayDeque0.add(option0);
      arrayDeque0.add(option0);
      // Undeclared exception!
      try { 
        helpFormatter0.sort((Iterable<Option>) arrayDeque0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.AbstractHelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder0);
      ArrayList<TextStyle> arrayList0 = new ArrayList<TextStyle>();
      TableDefinition tableDefinition0 = TableDefinition.from("ENUM$VALUES", arrayList0, (List<String>) null, (Iterable<List<String>>) null);
      // Undeclared exception!
      try { 
        helpFormatter0.printOptions(tableDefinition0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder0);
      // Undeclared exception!
      try { 
        helpFormatter0.printOptions((Options) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.AbstractHelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder0);
      // Undeclared exception!
      try { 
        helpFormatter0.printOptions((Iterable<Option>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp("", "", (Iterable<Option>) null, "", true);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.AbstractHelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      OptionGroup optionGroup0 = new OptionGroup();
      Option option0 = new Option("comparator", true, "usage: ");
      OptionGroup optionGroup1 = optionGroup0.addOption(option0);
      String string0 = helpFormatter0.toSyntaxOptions(optionGroup1);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
      assertEquals("[-comparator <arg>]", string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      OptionGroup optionGroup0 = new OptionGroup();
      helpFormatter0.toSyntaxOptions(optionGroup0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      HashMap<Option, TextHelpAppendable> hashMap0 = new HashMap<Option, TextHelpAppendable>();
      Option option0 = new Option("optionFormatBuilder", "optionFormatBuilder", true, "usage: ");
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      hashMap0.put(option0, textHelpAppendable0);
      Set<Option> set0 = hashMap0.keySet();
      Function<Option, OptionGroup> function0 = (Function<Option, OptionGroup>) mock(Function.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(function0).apply(any(org.apache.commons.cli.Option.class));
      String string0 = helpFormatter0.toSyntaxOptions((Iterable<Option>) set0, function0);
      assertEquals("[-optionFormatBuilder <arg>]", string0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      Class<Option> class0 = Option.class;
      ClassLoader classLoader0 = ClassLoader.getSystemClassLoader();
      ServiceLoader<Option> serviceLoader0 = ServiceLoader.load(class0, classLoader0);
      helpFormatter0.sort((Iterable<Option>) serviceLoader0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      helpFormatter0.sort((Iterable<Option>) null);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      Options options0 = new Options();
      helpFormatter0.printHelp("Error in script engine [%s] evaluating script [%s].", (String) null, options0, "org.junitpioneer.jupiter.CartesianEnumArgumentsProvider", true);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp("^Y$ryD XT,P<c}+5e", "org.junitpioneer.jupiter.cartesian.CartesianFactoryArgumentsProvider", (Options) null, "0r/UyRf d# 9WPs?b", false);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.AbstractHelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      Options options0 = new Options();
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp("", " ", options0, " nR7", false);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // cmdLineSyntax not provided
         //
         verifyException("org.apache.commons.cli.help.AbstractHelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      TreeSet<Option> treeSet0 = new TreeSet<Option>();
      TableDefinition tableDefinition0 = helpFormatter0.getTableDefinition(treeSet0);
      helpFormatter0.printOptions(tableDefinition0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      TreeSet<Option> treeSet0 = new TreeSet<Option>();
      helpFormatter0.printOptions((Iterable<Option>) treeSet0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      OptionGroup optionGroup0 = new OptionGroup();
      Option option0 = new Option((String) null, true, (String) null);
      optionGroup0.setRequired(true);
      OptionGroup optionGroup1 = optionGroup0.addOption(option0);
      String string0 = helpFormatter0.toSyntaxOptions(optionGroup1);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
      assertEquals(" <arg>", string0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder0);
      Options options0 = new Options();
      OptionGroup optionGroup0 = new OptionGroup();
      Option option0 = new Option((String) null, "", true, " | ");
      optionGroup0.addOption(option0);
      Option option1 = new Option((String) null, " | ", false, " | ");
      OptionGroup optionGroup1 = optionGroup0.addOption(option1);
      options0.addOptionGroup(optionGroup1);
      String string0 = helpFormatter0.toSyntaxOptions(options0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
      assertEquals("[ <arg> | -- | ]", string0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      HashMap<Option, TextHelpAppendable> hashMap0 = new HashMap<Option, TextHelpAppendable>();
      Option option0 = new Option("optionFormatBuilder", "optionFormatBuilder", true, "usage: ");
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      hashMap0.put(option0, textHelpAppendable0);
      Set<Option> set0 = hashMap0.keySet();
      OptionGroup optionGroup0 = new OptionGroup();
      Function<Option, OptionGroup> function0 = (Function<Option, OptionGroup>) mock(Function.class, new ViolatedAssumptionAnswer());
      doReturn(optionGroup0).when(function0).apply(any(org.apache.commons.cli.Option.class));
      String string0 = helpFormatter0.toSyntaxOptions((Iterable<Option>) set0, function0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      HashMap<Option, TextHelpAppendable> hashMap0 = new HashMap<Option, TextHelpAppendable>();
      Option option0 = new Option("optionFormatBuilder", "optionFormatBuilder", true, "usage: ");
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      hashMap0.put(option0, textHelpAppendable0);
      Set<Option> set0 = hashMap0.keySet();
      String string0 = helpFormatter0.toSyntaxOptions((Iterable<Option>) set0);
      assertEquals("[-optionFormatBuilder <arg>]", string0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      Options options0 = new Options();
      helpFormatter0.sort(options0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder0);
      helpFormatter0.sort((Options) null);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      Options options0 = new Options();
      Collection<Option> collection0 = options0.getOptions();
      ArrayDeque<Option> arrayDeque0 = new ArrayDeque<Option>(collection0);
      helpFormatter0.printHelp("comparator", (String) null, (Iterable<Option>) arrayDeque0, "", false);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setOptionFormatBuilder((OptionFormatter.Builder) null);
      assertSame(helpFormatter_Builder1, helpFormatter_Builder0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setHelpAppendable(textHelpAppendable0);
      assertSame(helpFormatter_Builder0, helpFormatter_Builder1);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setHelpAppendable((HelpAppendable) null);
      assertSame(helpFormatter_Builder1, helpFormatter_Builder0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder0);
      String string0 = helpFormatter0.toArgName("usage: ");
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
      assertEquals("<usage: >", string0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder0);
      String string0 = helpFormatter0.getSyntaxPrefix();
      assertEquals("usage: ", string0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      String string0 = helpFormatter0.getOptionGroupSeparator();
      assertEquals(" | ", string0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      helpFormatter0.getComparator();
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      HashMap<Option, TextHelpAppendable> hashMap0 = new HashMap<Option, TextHelpAppendable>();
      Set<Option> set0 = hashMap0.keySet();
      helpFormatter0.toSyntaxOptions((Iterable<Option>) set0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      helpFormatter0.getHelpAppendable();
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      Options options0 = new Options();
      helpFormatter0.toSyntaxOptions(options0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      helpFormatter0.getSerializer();
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      Options options0 = new Options();
      helpFormatter0.printOptions(options0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
      
      helpFormatter0.setSyntaxPrefix("");
      helpFormatter0.getSyntaxPrefix();
      assertEquals("", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      HashMap<Option, TextHelpAppendable> hashMap0 = new HashMap<Option, TextHelpAppendable>();
      Set<Option> set0 = hashMap0.keySet();
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp("", "@u2N=SLGJvT{{<", (Iterable<Option>) set0, "~v!0%cZ$x8,}Bh", true);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // cmdLineSyntax not provided
         //
         verifyException("org.apache.commons.cli.help.AbstractHelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      Comparator<Option> comparator0 = AbstractHelpFormatter.DEFAULT_COMPARATOR;
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setComparator(comparator0);
      assertSame(helpFormatter_Builder0, helpFormatter_Builder1);
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      OptionFormatter.Builder optionFormatter_Builder0 = helpFormatter0.getOptionFormatBuilder();
      helpFormatter_Builder0.setOptionFormatBuilder(optionFormatter_Builder0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }
}
