/*
 * This file was automatically generated by EvoSuite
 * Thu Mar 12 22:37:43 GMT 2026
 */

package org.apache.commons.cli.help;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.CharArrayWriter;
import java.nio.CharBuffer;
import java.util.ArrayList;
import java.util.Collection;
import java.util.LinkedHashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Locale;
import java.util.Stack;
import java.util.UnknownFormatConversionException;
import java.util.Vector;
import org.apache.commons.cli.help.TableDefinition;
import org.apache.commons.cli.help.TextHelpAppendable;
import org.apache.commons.cli.help.TextStyle;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.evosuite.runtime.mock.java.io.MockFileOutputStream;
import org.evosuite.runtime.mock.java.io.MockPrintStream;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class HelpAppendable_ESTest extends HelpAppendable_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      textHelpAppendable0.appendTitle("");
      assertEquals(74, textHelpAppendable0.getMaxWidth());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      Stack<TextStyle> stack0 = new Stack<TextStyle>();
      Vector<Locale.LanguageRange> vector0 = new Vector<Locale.LanguageRange>();
      LinkedHashSet<String> linkedHashSet0 = new LinkedHashSet<String>();
      Locale.FilteringMode locale_FilteringMode0 = Locale.FilteringMode.IGNORE_EXTENDED_RANGES;
      List<String> list0 = Locale.filterTags((List<Locale.LanguageRange>) vector0, (Collection<String>) linkedHashSet0, locale_FilteringMode0);
      LinkedList<List<String>> linkedList0 = new LinkedList<List<String>>();
      TableDefinition tableDefinition0 = TableDefinition.from("HKo-O", stack0, list0, linkedList0);
      textHelpAppendable0.appendTable(tableDefinition0);
      assertEquals(3, textHelpAppendable0.getIndent());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      CharArrayWriter charArrayWriter0 = new CharArrayWriter(0);
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(charArrayWriter0);
      textHelpAppendable0.appendParagraph("");
      assertEquals(3, textHelpAppendable0.getIndent());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      textHelpAppendable0.appendHeader(Integer.MAX_VALUE, "j3GxG6%RWK&G$y");
      assertEquals(1, TextHelpAppendable.DEFAULT_LEFT_PAD);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      textHelpAppendable0.appendList(true, (Collection<CharSequence>) null);
      assertEquals(3, TextHelpAppendable.DEFAULT_INDENT);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      char[] charArray0 = new char[9];
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      textHelpAppendable0.setLeftPad(Integer.MAX_VALUE);
      // Undeclared exception!
      textHelpAppendable0.appendTitle(charBuffer0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      ArrayList<String> arrayList0 = new ArrayList<String>();
      Stack<TextStyle> stack0 = new Stack<TextStyle>();
      arrayList0.add("");
      TableDefinition tableDefinition0 = TableDefinition.from("", stack0, arrayList0, (Iterable<List<String>>) null);
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendTable(tableDefinition0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 0, Size: 0
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      Stack<TextStyle> stack0 = new Stack<TextStyle>();
      Vector<Locale.LanguageRange> vector0 = new Vector<Locale.LanguageRange>();
      LinkedHashSet<String> linkedHashSet0 = new LinkedHashSet<String>();
      Locale.FilteringMode locale_FilteringMode0 = Locale.FilteringMode.IGNORE_EXTENDED_RANGES;
      List<String> list0 = Locale.filterTags((List<Locale.LanguageRange>) vector0, (Collection<String>) linkedHashSet0, locale_FilteringMode0);
      LinkedList<List<String>> linkedList0 = new LinkedList<List<String>>();
      TableDefinition tableDefinition0 = TableDefinition.from("HKo-O", stack0, list0, linkedList0);
      TextStyle.Builder textStyle_Builder0 = textHelpAppendable0.getTextStyleBuilder();
      textHelpAppendable0.resize(textStyle_Builder0, (-1.0));
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendTable(tableDefinition0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Width must be greater than 0
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      Object[] objectArray0 = new Object[6];
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendParagraphFormat("j3GxG6%RWK&G$y", objectArray0);
        fail("Expecting exception: UnknownFormatConversionException");
      
      } catch(UnknownFormatConversionException e) {
         //
         // Conversion = 'R'
         //
         verifyException("java.util.Formatter$FormatSpecifier", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendParagraphFormat((String) null, (Object[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      MockFile mockFile0 = new MockFile("+egDmJ", "+egDmJ");
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream(mockFile0, false);
      MockPrintStream mockPrintStream0 = new MockPrintStream(mockFileOutputStream0);
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(mockPrintStream0);
      textHelpAppendable0.setMaxWidth((-344));
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendParagraph("+egDmJ");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Width must be greater than 0
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable((Appendable) null);
      char[] charArray0 = new char[1];
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendHeader(32, charBuffer0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.FilterHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      CharArrayWriter charArrayWriter0 = new CharArrayWriter(0);
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(charArrayWriter0);
      textHelpAppendable0.setMaxWidth(0);
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendHeader(1142, "NC#uSM%),&Y*H");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Width must be greater than 0
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable((Appendable) null);
      Object[] objectArray0 = new Object[0];
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendFormat("<sW\"~Q)s]Ye5bB", objectArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.FilterHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      Object[] objectArray0 = new Object[6];
      textHelpAppendable0.appendParagraphFormat("XWcmrPO=3(0", objectArray0);
      assertEquals(1, TextHelpAppendable.DEFAULT_LEFT_PAD);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      CharArrayWriter charArrayWriter0 = new CharArrayWriter(0);
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(charArrayWriter0);
      Object[] objectArray0 = new Object[7];
      textHelpAppendable0.appendFormat("", objectArray0);
      assertEquals(1, textHelpAppendable0.getLeftPad());
  }
}
