/*
 * This file was automatically generated by EvoSuite
 * Thu Mar 12 22:39:32 GMT 2026
 */

package org.apache.commons.cli.help;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.PriorityQueue;
import java.util.Stack;
import java.util.TreeSet;
import java.util.Vector;
import org.apache.commons.cli.Option;
import org.apache.commons.cli.example.WeirdOptionFormat;
import org.apache.commons.cli.help.TableDefinition;
import org.apache.commons.cli.help.TextStyle;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TableDefinition_ESTest extends TableDefinition_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ArrayList<TextStyle> arrayList0 = new ArrayList<TextStyle>();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      TableDefinition tableDefinition0 = TableDefinition.from("", arrayList0, linkedList0, (Iterable<List<String>>) null);
      Iterable<List<String>> iterable0 = tableDefinition0.rows();
      assertNull(iterable0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      HashSet<TextStyle> hashSet0 = new HashSet<TextStyle>();
      ArrayList<TextStyle> arrayList0 = new ArrayList<TextStyle>(hashSet0);
      HashSet<List<String>> hashSet1 = new HashSet<List<String>>(3373707, 3373707);
      TableDefinition tableDefinition0 = TableDefinition.from("`", arrayList0, (List<String>) null, hashSet1);
      List<String> list0 = tableDefinition0.headers();
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Vector<TextStyle> vector0 = new Vector<TextStyle>();
      Vector<String> vector1 = new Vector<String>();
      HashSet<List<String>> hashSet0 = new HashSet<List<String>>(0);
      ArrayDeque<List<String>> arrayDeque0 = new ArrayDeque<List<String>>(hashSet0);
      TableDefinition tableDefinition0 = TableDefinition.from("", vector0, vector1, arrayDeque0);
      List<String> list0 = tableDefinition0.headers();
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Stack<TextStyle> stack0 = new Stack<TextStyle>();
      Stack<String> stack1 = new Stack<String>();
      stack1.add("org.apache.commons.cli.help.TableDefinition$1");
      Vector<List<String>> vector0 = new Vector<List<String>>(1756, 0);
      TableDefinition tableDefinition0 = TableDefinition.from("}(%Z", stack0, stack1, vector0);
      List<String> list0 = tableDefinition0.headers();
      assertTrue(list0.contains("org.apache.commons.cli.help.TableDefinition$1"));
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Vector<String> vector0 = new Vector<String>();
      Vector<List<String>> vector1 = new Vector<List<String>>(2340);
      TableDefinition tableDefinition0 = TableDefinition.from("b0gH0n#", (List<TextStyle>) null, vector0, vector1);
      List<TextStyle> list0 = tableDefinition0.columnTextStyles();
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Stack<TextStyle> stack0 = new Stack<TextStyle>();
      Vector<String> vector0 = new Vector<String>();
      TableDefinition tableDefinition0 = TableDefinition.from("n;4t", stack0, vector0, (Iterable<List<String>>) null);
      List<TextStyle> list0 = tableDefinition0.columnTextStyles();
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      TreeSet<Option> treeSet0 = new TreeSet<Option>();
      ArrayDeque<Option> arrayDeque0 = new ArrayDeque<Option>(treeSet0);
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) arrayDeque0);
      List<TextStyle> list0 = tableDefinition0.columnTextStyles();
      Stack<String> stack0 = new Stack<String>();
      PriorityQueue<List<String>> priorityQueue0 = new PriorityQueue<List<String>>();
      TableDefinition tableDefinition1 = TableDefinition.from((String) null, list0, stack0, priorityQueue0);
      String string0 = tableDefinition1.caption();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Stack<TextStyle> stack0 = new Stack<TextStyle>();
      Stack<String> stack1 = new Stack<String>();
      Vector<List<String>> vector0 = new Vector<List<String>>(1756, 0);
      TableDefinition tableDefinition0 = TableDefinition.from("}(%Z", stack0, stack1, vector0);
      String string0 = tableDefinition0.caption();
      assertEquals("}(%Z", string0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      ArrayList<Option> arrayList0 = new ArrayList<Option>();
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) arrayList0);
      Iterable<List<String>> iterable0 = tableDefinition0.rows();
      assertNotNull(iterable0);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      ArrayList<Option> arrayList0 = new ArrayList<Option>();
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) arrayList0);
      String string0 = tableDefinition0.caption();
      assertEquals("", string0);
  }
}
