/*
 * This file was automatically generated by EvoSuite
 * Fri Mar 13 23:56:49 GMT 2026
 */

package org.apache.commons.cli.help;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.nio.CharBuffer;
import java.nio.ReadOnlyBufferException;
import org.apache.commons.cli.help.Util;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Util_ESTest extends Util_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      CharBuffer charBuffer0 = CharBuffer.allocate(2640);
      Util.repeatSpace(2640);
      Util.ltrim("\"lvD/&:`Ses*");
      Util.indexOfNonWhitespace(charBuffer0, 5339);
      Util.ltrim(" W!*w/wY");
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Util.isWhitespace('<');
      String string0 = "org.apache.commons.cli.help.Util";
      Util.rtrim("org.apache.commons.cli.help.Util");
      CharBuffer charBuffer0 = CharBuffer.wrap((CharSequence) "org.apache.commons.cli.help.Util");
      int int0 = 2640;
      CharBuffer charBuffer1 = CharBuffer.allocate(2640);
      Util.indexOfNonWhitespace(charBuffer1, 372);
      Util.repeatSpace(372);
      Util.ltrim("\"lvD/&:`Ses*");
      charBuffer1.get();
      // Undeclared exception!
      try { 
        charBuffer0.put('*');
        fail("Expecting exception: ReadOnlyBufferException");
      
      } catch(ReadOnlyBufferException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.StringCharBuffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      String string0 = Util.repeatSpace(3099);
      Util.ltrim(string0);
      Util.isWhitespace('R');
      Util.defaultValue("", "");
      Util.ltrim(string0);
      Util.repeat(1, 'R');
      // Undeclared exception!
      try { 
        Util.repeatSpace((-2743));
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.Util", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Util.ltrim("");
      Util.isWhitespace(' ');
      Util.repeat(0, ' ');
      Util.isEmpty("");
      Util.ltrim("");
      Util.repeatSpace(0);
      Util.ltrim("vH&-o'+@, #");
      Util.defaultValue("vH&-o'+@, #", "vH&-o'+@, #");
      Util.ltrim("vH&-o'+@, #");
      Util.repeatSpace(1);
      Util.defaultValue("vH&-o'+@, #", "");
      Util.repeatSpace(1);
      Util.ltrim("maLY*ua#zz");
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      String string0 = Util.repeat(1715, 'U');
      String string1 = Util.repeat(1715, 'U');
      Util.ltrim(string1);
      Util.repeat(1715, 'U');
      Util.indexOfNonWhitespace(string0, 596);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      CharSequence charSequence0 = null;
      Util.isEmpty((CharSequence) null);
      Util.ltrim("k.");
      Util.ltrim((String) null);
      // Undeclared exception!
      try { 
        Util.indexOfNonWhitespace("k.", (-2719));
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Util.isWhitespace('g');
      char[] charArray0 = new char[4];
      charArray0[0] = 'g';
      charArray0[1] = 'g';
      charArray0[2] = 'g';
      charArray0[3] = 'g';
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      Util.indexOfNonWhitespace(charBuffer0, 0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Util.ltrim("");
      Util.defaultValue("ytDy5%fWX*+sFWTH", "");
      Util.ltrim("org.apache.commons.cli.help.Util");
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Util.defaultValue((String) null, (String) null);
      Util.repeatSpace(0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Util.ltrim("K_@0;2ldr/B");
      int int0 = (-1046);
      char char0 = '\\';
      // Undeclared exception!
      try { 
        Util.repeat((-1046), '\\');
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.Util", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Util.repeatSpace(0);
      Util.isEmpty("");
      Util.isEmpty("");
      Util.repeat(0, 'R');
      Util.isEmpty("");
      // Undeclared exception!
      try { 
        Util.repeatSpace((-78));
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.Util", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Util.defaultValue("", "");
      Util.isWhitespace(')');
      Util.rtrim("");
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      String string0 = Util.repeatSpace(1122);
      Util.indexOfNonWhitespace(string0, 1122);
      Util.rtrim("");
      Util.isEmpty("");
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Util.ltrim("");
      String string0 = Util.repeatSpace(1145);
      Util.repeat(1145, 'f');
      Util.isWhitespace('k');
      Util.defaultValue("", "W&`o-Ph]?| cN?");
      Util.rtrim("org.apache.commons.cli.help.Util");
      Util.indexOfNonWhitespace("org.apache.commons.cli.help.Util", 523);
      Util.rtrim(string0);
      Util.repeatSpace(1145);
      Util.repeatSpace(1005);
      Util.repeatSpace(32);
      Util.repeat(0, '6');
      Util.ltrim("W&`o-Ph]?| cN?");
      Util.isEmpty("W&`o-Ph]?| cN?");
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Util.rtrim("\"~8WGGMcTaH6sPAb<W;");
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Util.rtrim((String) null);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Util.repeatSpace(32);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Util.ltrim("06qy#i");
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Util.defaultValue("m'Y'-?aVw`/O6", "m'Y'-?aVw`/O6");
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Util.rtrim("");
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      String string0 = Util.repeatSpace(3068);
      Util.isEmpty(string0);
      String string1 = Util.rtrim(string0);
      String string2 = Util.repeat(3068, 'E');
      Util.isWhitespace('w');
      Util.repeat(0, 'E');
      int int0 = Util.indexOfNonWhitespace(string2, 278);
      assertEquals(278, int0);
      
      Util.isWhitespace('E');
      Util.ltrim("");
      String string3 = Util.repeatSpace(0);
      assertTrue(string3.equals((Object)string1));
      
      Util.isWhitespace('E');
      Util.rtrim("");
      Util.indexOfNonWhitespace("", (-365));
      Util.defaultValue("", "");
      Util.isWhitespace('w');
      Util.defaultValue("", "");
      Util.rtrim("");
      Util.rtrim("");
      Util.repeatSpace(278);
      CharBuffer charBuffer0 = CharBuffer.wrap((CharSequence) "");
      Util.defaultValue(charBuffer0, charBuffer0);
      Util.isEmpty("");
      Util.rtrim("");
      String string4 = Util.ltrim((String) null);
      assertTrue(string4.equals((Object)string1));
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Util.isWhitespace('<');
      CharBuffer charBuffer0 = CharBuffer.allocate(2640);
      String string0 = Util.ltrim("\"lvD/&:`Ses*");
      assertEquals("\"lvD/&:`Ses*", string0);
      
      int int0 = Util.indexOfNonWhitespace(charBuffer0, 5339);
      assertEquals((-1), int0);
      
      String string1 = Util.ltrim(" W!*w/wY");
      assertEquals("W!*w/wY", string1);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Util.rtrim("aAWQ7bwO%3CI|V6Zw");
      Util.rtrim("aAWQ7bwO%3CI|V6Zw");
      Util.rtrim("aAWQ7bwO%3CI|V6Zw");
      Util.isEmpty("aAWQ7bwO%3CI|V6Zw");
      Util.defaultValue("aAWQ7bwO%3CI|V6Zw", "aAWQ7bwO%3CI|V6Zw");
      Util.isEmpty("aAWQ7bwO%3CI|V6Zw");
      int int0 = Util.indexOfNonWhitespace("aAWQ7bwO%3CI|V6Zw", 21);
      assertEquals((-1), int0);
      
      Util.rtrim("aAWQ7bwO%3CI|V6Zw");
      Util.isWhitespace('\u0016');
      Util.rtrim("NCeitG p %pE|;");
      String string0 = Util.rtrim("aAWQ7bwO%3CI|V6Zw");
      assertEquals("aAWQ7bwO%3CI|V6Zw", string0);
      
      Util.ltrim("");
      boolean boolean0 = Util.isEmpty("aAWQ7bwO%3CI|V6Zw");
      assertFalse(boolean0);
  }
}
