/*
 * This file was automatically generated by EvoSuite
 * Thu Mar 12 22:09:17 GMT 2026
 */

package org.apache.commons.cli.help;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.BufferedWriter;
import java.io.ByteArrayOutputStream;
import java.io.CharArrayWriter;
import java.io.File;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.io.StringWriter;
import java.nio.ByteBuffer;
import java.nio.CharBuffer;
import java.nio.charset.Charset;
import java.nio.charset.CharsetEncoder;
import java.time.ZoneId;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Comparator;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Locale;
import java.util.NoSuchElementException;
import java.util.PriorityQueue;
import java.util.Queue;
import java.util.Set;
import java.util.SortedSet;
import java.util.Stack;
import java.util.TreeSet;
import java.util.Vector;
import java.util.function.Consumer;
import java.util.function.Function;
import java.util.function.UnaryOperator;
import org.apache.commons.cli.Option;
import org.apache.commons.cli.example.WeirdOptionFormat;
import org.apache.commons.cli.help.FilterHelpAppendable;
import org.apache.commons.cli.help.TableDefinition;
import org.apache.commons.cli.help.TextHelpAppendable;
import org.apache.commons.cli.help.TextStyle;
import org.apache.commons.text.similarity.LongestCommonSubsequence;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.evosuite.runtime.mock.java.io.MockFileOutputStream;
import org.evosuite.runtime.mock.java.io.MockFileWriter;
import org.evosuite.runtime.mock.java.io.MockPrintWriter;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TextHelpAppendable_ESTest extends TextHelpAppendable_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      char[] charArray0 = new char[0];
      MockFile mockFile0 = new MockFile("HYC'h[");
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("Width must be greater than 0");
      Charset charset0 = Charset.defaultCharset();
      CharsetEncoder charsetEncoder0 = charset0.newEncoder();
      OutputStreamWriter outputStreamWriter0 = new OutputStreamWriter(mockFileOutputStream0, charsetEncoder0);
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(outputStreamWriter0);
      textHelpAppendable0.appendHeader(764, "HYC'h[");
      ByteArrayOutputStream byteArrayOutputStream0 = new ByteArrayOutputStream(254);
      ObjectOutputStream objectOutputStream0 = new ObjectOutputStream(byteArrayOutputStream0);
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(objectOutputStream0);
      PrintWriter printWriter0 = mockPrintWriter0.append('A');
      TextHelpAppendable textHelpAppendable1 = new TextHelpAppendable(printWriter0);
      TextHelpAppendable.indexOfWrap("Width must be greater than 0", 7, 7);
      Locale locale0 = Locale.ITALY;
      locale0.getUnicodeLocaleAttributes();
      Stack<CharSequence> stack0 = new Stack<CharSequence>();
      textHelpAppendable1.appendList(true, stack0);
      // Undeclared exception!
      try { 
        CharBuffer.wrap(charArray0, 764, 2466);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.CharBuffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      String string0 = "org.apache.commons.io.filefilter.SizeFileFilter";
      MockFile mockFile0 = new MockFile("", "org.apache.commons.io.filefilter.SizeFileFilter");
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(mockFile0);
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(mockPrintWriter0);
      textHelpAppendable0.setMaxWidth((-180));
      int int0 = TextHelpAppendable.DEFAULT_LEFT_PAD;
      textHelpAppendable0.appendTitle("");
      textHelpAppendable0.appendHeader((-3957), "");
      textHelpAppendable0.getTextStyleBuilder();
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("D:\\University\\Semester 5 - Winter 2026\\EECS4313 - Software Engineering Testing\\Assignment 2\\EECS4313-Assignment2");
      FileSystemHandling.createFolder(evoSuiteFile0);
      mockFile0.setReadable(true);
      textHelpAppendable0.getLeftPad();
      ArrayList<Queue<String>> arrayList0 = new ArrayList<Queue<String>>();
      textHelpAppendable0.writeColumnQueues(arrayList0, (List<TextStyle>) null);
      Object[] objectArray0 = new Object[1];
      objectArray0[0] = (Object) mockPrintWriter0;
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendParagraphFormat("org.apache.commons.io.filefilter.SizeFileFilter", objectArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Width must be greater than 0
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      FileSystemHandling.shouldAllThrowIOExceptions();
      LinkedList<TextStyle> linkedList1 = new LinkedList<TextStyle>();
      textHelpAppendable0.makeColumnQueues(linkedList0, linkedList1);
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      LinkedHashSet<Option> linkedHashSet0 = new LinkedHashSet<Option>();
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) linkedHashSet0);
      TableDefinition tableDefinition1 = textHelpAppendable0.adjustTableFormat(tableDefinition0);
      TreeSet<List<String>> treeSet0 = new TreeSet<List<String>>();
      TreeSet<List<String>> treeSet1 = new TreeSet<List<String>>((SortedSet<List<String>>) treeSet0);
      textHelpAppendable0.adjustTableFormat(tableDefinition0);
      textHelpAppendable0.appendTable(tableDefinition1);
      TextHelpAppendable textHelpAppendable1 = TextHelpAppendable.systemOut();
      textHelpAppendable1.appendTable(tableDefinition1);
      LinkedList<CharSequence> linkedList2 = new LinkedList<CharSequence>();
      textHelpAppendable1.appendHeader(1, "C{k^QUQH;Ho*w[F^pKt");
      linkedList2.add((CharSequence) "C{k^QUQH;Ho*w[F^pKt");
      textHelpAppendable1.appendList(true, linkedList2);
      textHelpAppendable0.appendTable(tableDefinition0);
      textHelpAppendable1.getTextStyleBuilder();
      TextHelpAppendable.indexOfWrap("C{k^QUQH;Ho*w[F^pKt", 3, 3);
      TextHelpAppendable.systemOut();
      LinkedList<Queue<String>> linkedList3 = new LinkedList<Queue<String>>();
      linkedList3.add((Queue<String>) linkedList0);
      // Undeclared exception!
      try { 
        textHelpAppendable0.writeColumnQueues(linkedList3, linkedList1);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 0, Size: 0
         //
         verifyException("java.util.LinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      textHelpAppendable0.getMaxWidth();
      boolean boolean0 = false;
      String string0 = "I2qe:f'NI>Y`PQ:";
      TextStyle textStyle0 = TextStyle.DEFAULT;
      textHelpAppendable0.printWrapped("I2qe:f'NI>Y`PQ:", textStyle0);
      ArrayList<CharSequence> arrayList0 = new ArrayList<CharSequence>();
      textHelpAppendable0.setLeftPad(Integer.MAX_VALUE);
      arrayList0.add((CharSequence) "I2qe:f'NI>Y`PQ:");
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      TreeSet<Option> treeSet0 = new TreeSet<Option>();
      TreeSet<Option> treeSet1 = new TreeSet<Option>((SortedSet<Option>) treeSet0);
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) treeSet1);
      TableDefinition tableDefinition1 = textHelpAppendable0.adjustTableFormat(tableDefinition0);
      // Undeclared exception!
      textHelpAppendable0.appendTable(tableDefinition1);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      MockFileWriter mockFileWriter0 = new MockFileWriter("`y=SZ+;P*W%d^y#S4", true);
      BufferedWriter bufferedWriter0 = new BufferedWriter(mockFileWriter0, 4);
      TextStyle textStyle0 = TextStyle.DEFAULT;
      char[] charArray0 = new char[0];
      bufferedWriter0.write(charArray0);
      ArrayList<Queue<String>> arrayList0 = new ArrayList<Queue<String>>();
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      mockFileWriter0.close();
      PriorityQueue<Option> priorityQueue0 = new PriorityQueue<Option>();
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) priorityQueue0);
      priorityQueue0.parallelStream();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      ArrayList<List<String>> arrayList1 = new ArrayList<List<String>>();
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(bufferedWriter0);
      try { 
        textHelpAppendable0.appendTable(tableDefinition0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      int int0 = 35;
      StringWriter stringWriter0 = new StringWriter(35);
      CharBuffer charBuffer0 = CharBuffer.allocate(35);
      CharBuffer charBuffer1 = CharBuffer.wrap((CharSequence) charBuffer0);
      CharBuffer charBuffer2 = CharBuffer.wrap((CharSequence) charBuffer1, 0, 35);
      charBuffer2.get();
      stringWriter0.append((CharSequence) charBuffer2);
      StringBuffer stringBuffer0 = stringWriter0.getBuffer();
      charBuffer0.append((CharSequence) charBuffer1);
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(stringBuffer0);
      textHelpAppendable0.getMaxWidth();
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendTitle(charBuffer1);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      CharBuffer charBuffer0 = CharBuffer.allocate(1);
      charBuffer0.mark();
      TextHelpAppendable textHelpAppendable1 = TextHelpAppendable.systemOut();
      textHelpAppendable0.appendParagraph(charBuffer0);
      Stack<Option> stack0 = new Stack<Option>();
      LinkedHashSet<Option> linkedHashSet0 = new LinkedHashSet<Option>(stack0);
      stack0.stream();
      stack0.parallelStream();
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) linkedHashSet0);
      textHelpAppendable0.appendTable(tableDefinition0);
      TextStyle.Builder textStyle_Builder0 = textHelpAppendable0.getTextStyleBuilder();
      textHelpAppendable0.resize(textStyle_Builder0, (-1.0));
      Stack<String> stack1 = new Stack<String>();
      String string0 = "%s%n";
      stack1.add("%s%n");
      textHelpAppendable1.appendHeader(3, "%s%n");
      Vector<TextStyle> vector0 = null;
      try {
        vector0 = new Vector<TextStyle>((Collection<? extends TextStyle>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Vector", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      char[] charArray0 = new char[0];
      int int0 = 764;
      File file0 = MockFile.createTempFile("Width must be greater than 0", "HYC'h[");
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream(file0, false);
      Charset charset0 = Charset.defaultCharset();
      CharsetEncoder charsetEncoder0 = charset0.newEncoder();
      OutputStreamWriter outputStreamWriter0 = new OutputStreamWriter(mockFileOutputStream0, charsetEncoder0);
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(outputStreamWriter0);
      textHelpAppendable0.appendHeader(764, "HYC'h[");
      ByteArrayOutputStream byteArrayOutputStream0 = new ByteArrayOutputStream(254);
      ObjectOutputStream objectOutputStream0 = new ObjectOutputStream(byteArrayOutputStream0);
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(objectOutputStream0);
      mockPrintWriter0.append('A');
      TextHelpAppendable textHelpAppendable1 = TextHelpAppendable.systemOut();
      Locale locale0 = Locale.ITALY;
      Set<String> set0 = ZoneId.getAvailableZoneIds();
      Vector<CharSequence> vector0 = new Vector<CharSequence>(set0);
      // Undeclared exception!
      textHelpAppendable1.appendList(true, vector0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      textHelpAppendable0.setLeftPad((-2688));
      TextStyle textStyle0 = TextStyle.DEFAULT;
      char[] charArray0 = new char[3];
      charArray0[0] = 'a';
      textStyle0.toString();
      charArray0[2] = '\u0000';
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      textStyle0.pad(false, charBuffer0);
      CharBuffer charBuffer1 = CharBuffer.wrap((CharSequence) "a\u0000\u0000");
      charBuffer1.get(charArray0);
      textHelpAppendable0.appendHeader((-2688), charBuffer1);
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendTitle("a\u0000\u0000");
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.Util", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      CharBuffer charBuffer0 = CharBuffer.allocate(1);
      charBuffer0.mark();
      TextHelpAppendable.systemOut();
      textHelpAppendable0.appendParagraph(charBuffer0);
      Stack<Option> stack0 = new Stack<Option>();
      LinkedHashSet<Option> linkedHashSet0 = new LinkedHashSet<Option>(stack0);
      stack0.parallelStream();
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) linkedHashSet0);
      textHelpAppendable0.appendTable(tableDefinition0);
      TextStyle.Builder textStyle_Builder0 = textHelpAppendable0.getTextStyleBuilder();
      textStyle_Builder0.setScalable(false);
      textHelpAppendable0.resize(textStyle_Builder0, (-1.0));
      Stack<String> stack1 = new Stack<String>();
      String string0 = "%s%n";
      stack1.add("%s%n");
      Vector<TextStyle> vector0 = null;
      try {
        vector0 = new Vector<TextStyle>((Collection<? extends TextStyle>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Vector", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      FileSystemHandling.shouldAllThrowIOExceptions();
      LinkedList<TextStyle> linkedList1 = new LinkedList<TextStyle>();
      textHelpAppendable0.makeColumnQueues(linkedList0, linkedList1);
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      LinkedHashSet<Option> linkedHashSet0 = new LinkedHashSet<Option>();
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) linkedHashSet0);
      TableDefinition tableDefinition1 = textHelpAppendable0.adjustTableFormat(tableDefinition0);
      TreeSet<List<String>> treeSet0 = new TreeSet<List<String>>();
      TreeSet<List<String>> treeSet1 = new TreeSet<List<String>>((SortedSet<List<String>>) treeSet0);
      textHelpAppendable0.adjustTableFormat(tableDefinition0);
      textHelpAppendable0.appendTable(tableDefinition1);
      TextHelpAppendable textHelpAppendable1 = TextHelpAppendable.systemOut();
      textHelpAppendable1.appendTable(tableDefinition1);
      LinkedList<CharSequence> linkedList2 = new LinkedList<CharSequence>();
      TextHelpAppendable.systemOut();
      linkedList2.add((CharSequence) "C{k^QUQH;Ho*w[F^pKt");
      linkedList2.add((CharSequence) "C{k^QUQH;Ho*w[F^pKt");
      textHelpAppendable1.appendList(true, linkedList2);
      textHelpAppendable0.appendTable(tableDefinition0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      textHelpAppendable0.setLeftPad((-2688));
      TextStyle textStyle0 = TextStyle.DEFAULT;
      textStyle0.toString();
      FileSystemHandling.shouldThrowIOException((EvoSuiteFile) null);
      char[] charArray0 = new char[3];
      charArray0[0] = 'a';
      charArray0[1] = 'T';
      charArray0[2] = 'T';
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      textStyle0.pad(false, charBuffer0);
      textHelpAppendable0.getLeftPad();
      CharBuffer charBuffer1 = CharBuffer.wrap((CharSequence) "aTT");
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendHeader((-2688), charBuffer1);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // level must be at least 1
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      int int0 = (-2688);
      textHelpAppendable0.setLeftPad((-2688));
      textHelpAppendable0.setLeftPad((-2688));
      TextStyle textStyle0 = TextStyle.DEFAULT;
      textStyle0.toString();
      char[] charArray0 = new char[3];
      charArray0[0] = 'a';
      charArray0[1] = 'T';
      charArray0[2] = 'T';
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      textStyle0.pad(false, charBuffer0);
      CharBuffer.wrap((CharSequence) "aTT");
      Stack<String> stack0 = new Stack<String>();
      Vector<TextStyle> vector0 = new Vector<TextStyle>();
      List<Queue<String>> list0 = textHelpAppendable0.makeColumnQueues(stack0, vector0);
      // Undeclared exception!
      try { 
        textHelpAppendable0.writeColumnQueues(list0, vector0);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.Util", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      textHelpAppendable0.setLeftPad((-2688));
      TextStyle textStyle0 = TextStyle.DEFAULT;
      textStyle0.toString();
      char[] charArray0 = new char[3];
      charArray0[0] = 'n';
      charArray0[1] = 'T';
      charArray0[2] = '`';
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      textStyle0.pad(false, charBuffer0);
      CharBuffer charBuffer1 = CharBuffer.allocate(74);
      charBuffer1.asReadOnlyBuffer();
      textHelpAppendable0.getTextStyleBuilder();
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendHeader((-2688), charBuffer1);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // level must be at least 1
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      textHelpAppendable0.getIndent();
      FileSystemHandling.shouldAllThrowIOExceptions();
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      Stack<Option> stack0 = new Stack<Option>();
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) stack0);
      TableDefinition tableDefinition1 = textHelpAppendable0.adjustTableFormat(tableDefinition0);
      Stack<TextStyle> stack1 = new Stack<TextStyle>();
      Stack<String> stack2 = new Stack<String>();
      TreeSet<List<String>> treeSet0 = new TreeSet<List<String>>();
      TableDefinition.from(" * %s", stack1, stack2, treeSet0);
      TableDefinition.from("[LFOe{*czRi)4B6M", stack1, stack2, treeSet0);
      textHelpAppendable0.setIndent((-11));
      textHelpAppendable0.adjustTableFormat(tableDefinition1);
      textHelpAppendable0.getIndent();
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      CharArrayWriter charArrayWriter0 = new CharArrayWriter();
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(charArrayWriter0);
      TextStyle textStyle0 = TextStyle.DEFAULT;
      CharBuffer charBuffer0 = CharBuffer.allocate(3);
      textStyle0.pad(false, charBuffer0);
      textHelpAppendable0.appendParagraph("\u0000\u0000\u0000");
      Stack<String> stack0 = new Stack<String>();
      Stack<TextStyle> stack1 = new Stack<TextStyle>();
      Stack<List<String>> stack2 = new Stack<List<String>>();
      Vector<List<String>> vector0 = new Vector<List<String>>(stack2);
      TableDefinition tableDefinition0 = TableDefinition.from(">OI`kk_APV80 7pYcb)", stack1, stack0, vector0);
      List<TextStyle> list0 = tableDefinition0.columnTextStyles();
      textHelpAppendable0.makeColumnQueues(stack0, list0);
      textHelpAppendable0.getTextStyleBuilder();
      TextHelpAppendable.indexOfWrap("\u0000\u0000\u0000", 1420, Integer.MAX_VALUE);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable((Appendable) null);
      Set<String> set0 = ZoneId.getAvailableZoneIds();
      TreeSet<CharSequence> treeSet0 = new TreeSet<CharSequence>(set0);
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendList(true, treeSet0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.FilterHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      CharBuffer charBuffer0 = CharBuffer.allocate(1);
      charBuffer0.mark();
      TextHelpAppendable textHelpAppendable1 = TextHelpAppendable.systemOut();
      textHelpAppendable0.appendParagraph(charBuffer0);
      Stack<Option> stack0 = new Stack<Option>();
      LinkedHashSet<Option> linkedHashSet0 = new LinkedHashSet<Option>(stack0);
      stack0.parallelStream();
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) linkedHashSet0);
      textHelpAppendable0.appendTable(tableDefinition0);
      TextStyle.Builder textStyle_Builder0 = textHelpAppendable0.getTextStyleBuilder();
      textHelpAppendable0.resize(textStyle_Builder0, (-22.4666798));
      String string0 = "%s%n";
      Consumer<Object> consumer0 = (Consumer<Object>) mock(Consumer.class, new ViolatedAssumptionAnswer());
      textHelpAppendable1.getIndent();
      textHelpAppendable1.getMaxWidth();
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendParagraph("%s%n");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Width must be greater than 0
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      TextStyle textStyle0 = TextStyle.DEFAULT;
      ArrayList<CharSequence> arrayList0 = new ArrayList<CharSequence>();
      textHelpAppendable0.setLeftPad(Integer.MAX_VALUE);
      textStyle0.toString();
      textStyle0.toString();
      textHelpAppendable0.appendList(false, arrayList0);
      textHelpAppendable0.getLeftPad();
      textHelpAppendable0.getTextStyleBuilder();
      LinkedList<Queue<String>> linkedList0 = new LinkedList<Queue<String>>();
      Vector<TextStyle> vector0 = new Vector<TextStyle>();
      // Undeclared exception!
      textHelpAppendable0.writeColumnQueues(linkedList0, vector0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      FileSystemHandling.shouldAllThrowIOExceptions();
      LinkedList<TextStyle> linkedList1 = new LinkedList<TextStyle>();
      textHelpAppendable0.makeColumnQueues(linkedList0, linkedList1);
      FileSystemHandling.shouldThrowIOException((EvoSuiteFile) null);
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      LinkedHashSet<Option> linkedHashSet0 = new LinkedHashSet<Option>();
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) linkedHashSet0);
      TableDefinition tableDefinition1 = textHelpAppendable0.adjustTableFormat(tableDefinition0);
      TreeSet<List<String>> treeSet0 = new TreeSet<List<String>>();
      TreeSet<List<String>> treeSet1 = new TreeSet<List<String>>((SortedSet<List<String>>) treeSet0);
      TableDefinition.from("C{k^QUQH;Ho*w[F^pKt", linkedList1, linkedList0, treeSet1);
      textHelpAppendable0.appendTable(tableDefinition1);
      TextHelpAppendable textHelpAppendable1 = TextHelpAppendable.systemOut();
      textHelpAppendable1.makeColumnQueues(linkedList0, linkedList1);
      textHelpAppendable1.appendTable(tableDefinition1);
      LinkedList<CharSequence> linkedList2 = new LinkedList<CharSequence>();
      linkedList2.add((CharSequence) "C{k^QUQH;Ho*w[F^pKt");
      textHelpAppendable1.appendList(false, linkedList2);
      textHelpAppendable0.appendTable(tableDefinition0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      Object[] objectArray0 = new Object[6];
      objectArray0[0] = (Object) textHelpAppendable0;
      objectArray0[1] = (Object) "org.apache.commons.io.filefilter.OrFileFilter";
      objectArray0[2] = (Object) textHelpAppendable0;
      Object object0 = new Object();
      objectArray0[3] = object0;
      objectArray0[4] = (Object) "org.apache.commons.io.filefilter.OrFileFilter";
      objectArray0[5] = (Object) textHelpAppendable0;
      textHelpAppendable0.appendFormat("org.apache.commons.io.filefilter.OrFileFilter", objectArray0);
      textHelpAppendable0.setIndent((-1892));
      textHelpAppendable0.getLeftPad();
      textHelpAppendable0.getTextStyleBuilder();
      LinkedList<CharSequence> linkedList0 = new LinkedList<CharSequence>();
      textHelpAppendable0.appendList(true, linkedList0);
      LinkedList<String> linkedList1 = new LinkedList<String>();
      ArrayList<TextStyle> arrayList0 = new ArrayList<TextStyle>();
      linkedList1.add("PX/40C)w");
      // Undeclared exception!
      try { 
        textHelpAppendable0.makeColumnQueues(linkedList1, arrayList0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 0, Size: 0
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      CharArrayWriter charArrayWriter0 = new CharArrayWriter();
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(charArrayWriter0);
      TextStyle textStyle0 = TextStyle.DEFAULT;
      CharBuffer charBuffer0 = CharBuffer.allocate(3);
      textStyle0.pad(false, charBuffer0);
      textHelpAppendable0.appendParagraph("\u0000\u0000\u0000");
      Stack<String> stack0 = new Stack<String>();
      Stack<TextStyle> stack1 = new Stack<TextStyle>();
      Stack<List<String>> stack2 = new Stack<List<String>>();
      Vector<List<String>> vector0 = new Vector<List<String>>(stack2);
      TableDefinition tableDefinition0 = TableDefinition.from(">OI`kk_APV80 7pYcb)", stack1, stack0, vector0);
      List<TextStyle> list0 = tableDefinition0.columnTextStyles();
      List<Queue<String>> list1 = textHelpAppendable0.makeColumnQueues(stack0, list0);
      textHelpAppendable0.writeColumnQueues(list1, list0);
      // Undeclared exception!
      try { 
        TextHelpAppendable.indexOfWrap("\u0000\u0000\u0000", 13, (-1));
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      textHelpAppendable0.getTextStyleBuilder();
      textHelpAppendable0.setMaxWidth(0);
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      Vector<Option> vector0 = new Vector<Option>();
      Option option0 = mock(Option.class, new ViolatedAssumptionAnswer());
      doReturn("pathMatcher").when(option0).getArgName();
      doReturn((String) null).when(option0).getDescription();
      doReturn("pathMatcher").when(option0).getLongOpt();
      doReturn("pathMatcher").when(option0).getOpt();
      doReturn("pathMatcher").when(option0).getSince();
      doReturn("pathMatcher").when(option0).getType();
      doReturn("pathMatcher").when(option0).getValue();
      doReturn(true).when(option0).hasArg();
      doReturn(true).when(option0).isDeprecated();
      doReturn(true).when(option0).isRequired();
      vector0.add(option0);
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) vector0);
      textHelpAppendable0.getTextStyleBuilder();
      String string0 = "";
      TextStyle textStyle0 = TextStyle.DEFAULT;
      textHelpAppendable0.printWrapped("", textStyle0);
      List<TextStyle> list0 = tableDefinition0.columnTextStyles();
      Stack<Locale.LanguageRange> stack0 = new Stack<Locale.LanguageRange>();
      HashSet<String> hashSet0 = new HashSet<String>();
      textHelpAppendable0.setMaxWidth((-2));
      Locale.FilteringMode locale_FilteringMode0 = Locale.FilteringMode.IGNORE_EXTENDED_RANGES;
      List<String> list1 = Locale.filterTags((List<Locale.LanguageRange>) stack0, (Collection<String>) hashSet0, locale_FilteringMode0);
      TableDefinition tableDefinition1 = TableDefinition.from("pathMatcher", list0, list1, (Iterable<List<String>>) null);
      // Undeclared exception!
      try { 
        textHelpAppendable0.adjustTableFormat(tableDefinition1);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 0, Size: 0
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      textHelpAppendable0.getMaxWidth();
      boolean boolean0 = false;
      String string0 = "I2qe:f'NI>Y`PQ:";
      TextStyle textStyle0 = TextStyle.DEFAULT;
      textHelpAppendable0.printWrapped("I2qe:f'NI>Y`PQ:", textStyle0);
      ArrayList<CharSequence> arrayList0 = new ArrayList<CharSequence>();
      textHelpAppendable0.setLeftPad(Integer.MAX_VALUE);
      arrayList0.add((CharSequence) "I2qe:f'NI>Y`PQ:");
      textStyle0.toString();
      // Undeclared exception!
      textHelpAppendable0.appendList(false, arrayList0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      TextHelpAppendable textHelpAppendable1 = TextHelpAppendable.systemOut();
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      PriorityQueue<Option> priorityQueue0 = new PriorityQueue<Option>();
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) priorityQueue0);
      TableDefinition tableDefinition1 = textHelpAppendable1.adjustTableFormat(tableDefinition0);
      textHelpAppendable0.appendTable(tableDefinition1);
      CharBuffer charBuffer0 = CharBuffer.allocate(1);
      CharBuffer charBuffer1 = CharBuffer.wrap((CharSequence) charBuffer0);
      // Undeclared exception!
      try { 
        TextHelpAppendable.indexOfWrap(charBuffer1, 74, (-512));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      CharArrayWriter charArrayWriter0 = new CharArrayWriter();
      char[] charArray0 = new char[6];
      charArray0[0] = 's';
      charArray0[1] = 'z';
      charArray0[2] = '9';
      charArray0[3] = '*';
      charArray0[4] = 'E';
      charArray0[5] = 'G';
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      CharArrayWriter charArrayWriter1 = charArrayWriter0.append((CharSequence) charBuffer0, 1, 1);
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(charArrayWriter1);
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.add("");
      Stack<TextStyle> stack0 = new Stack<TextStyle>();
      // Undeclared exception!
      try { 
        textHelpAppendable0.makeColumnQueues(linkedList0, stack0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Array index out of range: 0
         //
         verifyException("java.util.Vector", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      FileSystemHandling.appendStringToFile((EvoSuiteFile) null, "?FZ6O|;|");
      Object[] objectArray0 = new Object[0];
      textHelpAppendable0.appendFormat("", objectArray0);
      int int0 = 0;
      textHelpAppendable0.setIndent(0);
      Charset.defaultCharset();
      byte[] byteArray0 = new byte[3];
      byteArray0[0] = (byte)0;
      FileSystemHandling.createFolder((EvoSuiteFile) null);
      byteArray0[1] = (byte)8;
      byte byte0 = (byte)14;
      byteArray0[2] = (byte)14;
      TreeSet<CharSequence> treeSet0 = new TreeSet<CharSequence>();
      textHelpAppendable0.appendList(true, treeSet0);
      textHelpAppendable0.getIndent();
      // Undeclared exception!
      try { 
        ByteBuffer.wrap(byteArray0, 10, 0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.ByteBuffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      Object[] objectArray0 = new Object[7];
      Object object0 = new Object();
      objectArray0[0] = object0;
      objectArray0[1] = (Object) "bI@_E$gj=|NgXB[a'u!";
      objectArray0[2] = (Object) textHelpAppendable0;
      objectArray0[3] = (Object) textHelpAppendable0;
      objectArray0[4] = (Object) "bI@_E$gj=|NgXB[a'u!";
      objectArray0[5] = (Object) "bI@_E$gj=|NgXB[a'u!";
      objectArray0[6] = (Object) textHelpAppendable0;
      textHelpAppendable0.appendParagraphFormat("bI@_E$gj=|NgXB[a'u!", objectArray0);
      char[] charArray0 = new char[0];
      textHelpAppendable0.getLeftPad();
      textHelpAppendable0.getIndent();
      LinkedList<TextStyle> linkedList0 = new LinkedList<TextStyle>();
      Stack<String> stack0 = new Stack<String>();
      TextStyle textStyle0 = TextStyle.DEFAULT;
      linkedList0.add(textStyle0);
      TreeSet<List<String>> treeSet0 = new TreeSet<List<String>>();
      PriorityQueue<List<String>> priorityQueue0 = new PriorityQueue<List<String>>((SortedSet<? extends List<String>>) treeSet0);
      TableDefinition tableDefinition0 = TableDefinition.from("e2;MiX_o$W_", linkedList0, stack0, priorityQueue0);
      // Undeclared exception!
      try { 
        textHelpAppendable0.adjustTableFormat(tableDefinition0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Array index out of range: 0
         //
         verifyException("java.util.Vector", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable((Appendable) null);
      textHelpAppendable0.getTextStyleBuilder();
      char[] charArray0 = new char[1];
      charArray0[0] = '^';
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendHeader(92, charBuffer0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.FilterHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      int int0 = 0;
      textHelpAppendable0.setMaxWidth(0);
      textHelpAppendable0.append('L');
      textHelpAppendable0.setMaxWidth(3373707);
      String string0 = "X";
      int int1 = 115;
      textHelpAppendable0.append((CharSequence) "X");
      // Undeclared exception!
      textHelpAppendable0.appendTitle("X");
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable((Appendable) null);
      textHelpAppendable0.setMaxWidth((-362));
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      textStyle_Builder0.setMinWidth((-1293));
      textStyle_Builder0.get();
      textHelpAppendable0.resize(textStyle_Builder0, (-362));
      CharSequence charSequence0 = null;
      TextStyle textStyle0 = TextStyle.DEFAULT;
      // Undeclared exception!
      try { 
        textHelpAppendable0.makeColumnQueue((CharSequence) null, textStyle0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      textHelpAppendable0.setMaxWidth(0);
      textHelpAppendable0.setMaxWidth(0);
      textHelpAppendable0.getMaxWidth();
      textHelpAppendable0.setIndent(0);
      LongestCommonSubsequence longestCommonSubsequence0 = new LongestCommonSubsequence();
      TextStyle textStyle0 = TextStyle.DEFAULT;
      boolean boolean0 = true;
      StringWriter stringWriter0 = new StringWriter(Integer.MAX_VALUE);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      LongestCommonSubsequence longestCommonSubsequence0 = new LongestCommonSubsequence();
      TextStyle textStyle0 = TextStyle.DEFAULT;
      char[] charArray0 = new char[5];
      charArray0[0] = '/';
      charArray0[1] = '@';
      charArray0[2] = '5';
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      textStyle0.pad(false, charBuffer0);
      charArray0[3] = 'k';
      charArray0[4] = '^';
      CharBuffer charBuffer1 = CharBuffer.wrap(charArray0);
      CharBuffer charBuffer2 = CharBuffer.wrap((CharSequence) charBuffer1);
      textStyle0.pad(false, charBuffer2);
      longestCommonSubsequence0.longestCommonSubsequence("/@5k^", charBuffer2);
      textHelpAppendable0.makeColumnQueue("/@5k^", textStyle0);
      Vector<TextStyle> vector0 = new Vector<TextStyle>();
      // Undeclared exception!
      try { 
        textHelpAppendable0.makeColumnQueues((List<String>) null, vector0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      textStyle_Builder0.setMaxWidth(3);
      textStyle_Builder0.get();
      textStyle_Builder0.get();
      TextStyle.Builder textStyle_Builder1 = textHelpAppendable0.resize(textStyle_Builder0, 1.0);
      TextStyle.Alignment textStyle_Alignment0 = TextStyle.Alignment.RIGHT;
      textStyle_Builder1.setAlignment(textStyle_Alignment0);
      textStyle_Builder1.get();
      textStyle_Builder1.setMinWidth(61);
      textStyle_Builder1.setScalable(true);
      textHelpAppendable0.resize(textStyle_Builder1, 1.0);
      textHelpAppendable0.getLeftPad();
      TextHelpAppendable.systemOut();
      // Undeclared exception!
      try { 
        CharBuffer.wrap((char[]) null, 1, 1599);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.HeapCharBuffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable((Appendable) null);
      TextHelpAppendable textHelpAppendable1 = TextHelpAppendable.systemOut();
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      ArrayDeque<Option> arrayDeque0 = new ArrayDeque<Option>(95);
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) arrayDeque0);
      TableDefinition tableDefinition1 = textHelpAppendable1.adjustTableFormat(tableDefinition0);
      List<String> list0 = tableDefinition1.headers();
      List<TextStyle> list1 = tableDefinition1.columnTextStyles();
      Vector<String> vector0 = new Vector<String>();
      TreeSet<List<String>> treeSet0 = new TreeSet<List<String>>();
      LinkedHashSet<List<String>> linkedHashSet0 = new LinkedHashSet<List<String>>(treeSet0);
      TableDefinition tableDefinition2 = TableDefinition.from("Xcl^5W}tWk4", list1, vector0, linkedHashSet0);
      List<TextStyle> list2 = tableDefinition2.columnTextStyles();
      textHelpAppendable0.makeColumnQueues(list0, list2);
      // Undeclared exception!
      try { 
        textHelpAppendable1.appendTable(tableDefinition2);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Array index out of range: 0
         //
         verifyException("java.util.Vector", e);
      }
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      TextStyle textStyle0 = TextStyle.DEFAULT;
      CharBuffer charBuffer0 = CharBuffer.allocate(0);
      textStyle0.pad(false, charBuffer0);
      textHelpAppendable0.appendParagraph("");
      ArrayList<CharSequence> arrayList0 = new ArrayList<CharSequence>();
      textHelpAppendable0.appendList(false, arrayList0);
      textHelpAppendable0.printWrapped("");
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      textHelpAppendable0.setLeftPad(0);
      textHelpAppendable0.getLeftPad();
      char[] charArray0 = new char[0];
      // Undeclared exception!
      try { 
        CharBuffer.wrap(charArray0, 3, (-1175));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.CharBuffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      StringWriter stringWriter0 = new StringWriter(416);
      StringWriter stringWriter1 = stringWriter0.append('t');
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(stringWriter1);
      char[] charArray0 = new char[9];
      charArray0[0] = 't';
      charArray0[1] = 't';
      charArray0[2] = 't';
      charArray0[3] = 't';
      charArray0[4] = 't';
      charArray0[5] = 'y';
      charArray0[6] = 't';
      charArray0[7] = 't';
      charArray0[8] = 't';
      stringWriter1.write(charArray0);
      LinkedList<String> linkedList0 = new LinkedList<String>();
      LinkedList<TextStyle> linkedList1 = new LinkedList<TextStyle>();
      List<Queue<String>> list0 = textHelpAppendable0.makeColumnQueues(linkedList0, linkedList1);
      textHelpAppendable0.writeColumnQueues(list0, linkedList1);
      stringWriter1.write(charArray0);
      ArrayList<Queue<String>> arrayList0 = new ArrayList<Queue<String>>();
      LinkedList<TextStyle> linkedList2 = new LinkedList<TextStyle>();
      textHelpAppendable0.writeColumnQueues(arrayList0, linkedList2);
      TextStyle textStyle0 = TextStyle.DEFAULT;
      linkedList2.add(textStyle0);
      textHelpAppendable0.getIndent();
      TableDefinition tableDefinition0 = TableDefinition.from("jt:`*pr Ur", linkedList2, linkedList0, (Iterable<List<String>>) null);
      TableDefinition.from("K1QENBE", linkedList1, linkedList0, (Iterable<List<String>>) null);
      // Undeclared exception!
      try { 
        textHelpAppendable0.adjustTableFormat(tableDefinition0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 0, Size: 0
         //
         verifyException("java.util.LinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable((Appendable) null);
      LinkedList<Queue<String>> linkedList0 = new LinkedList<Queue<String>>();
      LinkedList<TextStyle> linkedList1 = new LinkedList<TextStyle>();
      // Undeclared exception!
      try { 
        textHelpAppendable0.writeColumnQueues(linkedList0, linkedList1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      MockFileWriter mockFileWriter0 = new MockFileWriter("`y=SZ+;P*W%d^y#S4", true);
      BufferedWriter bufferedWriter0 = new BufferedWriter(mockFileWriter0, 4);
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(bufferedWriter0);
      TextStyle textStyle0 = TextStyle.DEFAULT;
      textHelpAppendable0.makeColumnQueue("`y=SZ+;P*W%d^y#S4", textStyle0);
      char[] charArray0 = new char[0];
      bufferedWriter0.write(charArray0);
      ArrayList<Queue<String>> arrayList0 = new ArrayList<Queue<String>>();
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      mockFileWriter0.close();
      PriorityQueue<Option> priorityQueue0 = new PriorityQueue<Option>();
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) priorityQueue0);
      TableDefinition tableDefinition1 = textHelpAppendable0.adjustTableFormat(tableDefinition0);
      List<TextStyle> list0 = tableDefinition1.columnTextStyles();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      ArrayList<List<String>> arrayList1 = new ArrayList<List<String>>();
      TableDefinition.from("`y=SZ+;P*W%d^y#S4", list0, linkedList0, arrayList1);
      List<TextStyle> list1 = tableDefinition1.columnTextStyles();
      textHelpAppendable0.writeColumnQueues(arrayList0, list1);
      textHelpAppendable0.getMaxWidth();
      textHelpAppendable0.adjustTableFormat(tableDefinition0);
      try { 
        textHelpAppendable0.printWrapped("org.apache.commons.text.similarity.HammingDistance");
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
      }
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      textHelpAppendable0.getIndent();
      CharBuffer charBuffer0 = CharBuffer.allocate(1);
      char[] charArray0 = new char[3];
      charArray0[0] = 'U';
      charArray0[1] = '3';
      charArray0[2] = 'o';
      CharBuffer.wrap(charArray0);
      textHelpAppendable0.setMaxWidth(0);
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendTitle(charBuffer0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Width must be greater than 0
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      Stack<Queue<String>> stack0 = new Stack<Queue<String>>();
      PriorityQueue<String> priorityQueue0 = new PriorityQueue<String>();
      priorityQueue0.add("");
      stack0.add((Queue<String>) priorityQueue0);
      Stack<TextStyle> stack1 = new Stack<TextStyle>();
      // Undeclared exception!
      try { 
        textHelpAppendable0.writeColumnQueues(stack0, stack1);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Array index out of range: 0
         //
         verifyException("java.util.Vector", e);
      }
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      TextHelpAppendable.systemOut();
      TextHelpAppendable.systemOut();
      // Undeclared exception!
      try { 
        TextHelpAppendable.indexOfWrap((CharSequence) null, 1, 98);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      StringWriter stringWriter0 = new StringWriter(35);
      int int0 = 1419;
      CharBuffer charBuffer0 = CharBuffer.allocate(1419);
      CharBuffer charBuffer1 = CharBuffer.wrap((CharSequence) charBuffer0);
      CharBuffer charBuffer2 = CharBuffer.wrap((CharSequence) charBuffer1, 0, 35);
      charBuffer2.get();
      stringWriter0.append((CharSequence) charBuffer2);
      StringBuffer stringBuffer0 = stringWriter0.getBuffer();
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(stringBuffer0);
      textHelpAppendable0.getMaxWidth();
      textHelpAppendable0.appendTitle(charBuffer1);
      textHelpAppendable0.setMaxWidth(35);
      textHelpAppendable0.setIndent(74);
      char[] charArray0 = new char[8];
      charArray0[0] = '\u0000';
      charArray0[1] = '\u0000';
      charArray0[2] = '\u0000';
      charArray0[3] = '\u0000';
      charArray0[4] = '\u0000';
      charArray0[5] = '\u0000';
      charArray0[6] = '\u0000';
      charArray0[7] = 'A';
      stringWriter0.write(charArray0);
      // Undeclared exception!
      try { 
        TextHelpAppendable.indexOfWrap(stringBuffer0, 0, 0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Width must be greater than 0
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      textStyle_Builder0.setLeftPad(1);
      textStyle_Builder0.setLeftPad((-2044));
      textHelpAppendable0.resize(textStyle_Builder0, 629.35);
      int int0 = 2629;
      CharBuffer charBuffer0 = CharBuffer.allocate(2629);
      charBuffer0.codePoints();
      TextHelpAppendable.indexOfWrap(charBuffer0, 74, 74);
      // Undeclared exception!
      try { 
        textHelpAppendable0.adjustTableFormat((TableDefinition) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      int int0 = 2;
      textHelpAppendable0.setLeftPad(2);
      textHelpAppendable0.setIndent((-2631));
      String string0 = null;
      // Undeclared exception!
      try { 
        textHelpAppendable0.printWrapped((String) null);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.Util", e);
      }
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable((Appendable) null);
      TextStyle textStyle0 = TextStyle.DEFAULT;
      char[] charArray0 = new char[8];
      charArray0[0] = 'G';
      charArray0[1] = '#';
      charArray0[2] = '~';
      charArray0[3] = 'J';
      charArray0[4] = 'S';
      charArray0[5] = 'x';
      charArray0[6] = '(';
      charArray0[7] = 'H';
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      textStyle0.pad(false, charBuffer0);
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendTitle("G#~JSx(H");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.FilterHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      StringWriter stringWriter0 = new StringWriter(0);
      StringBuffer stringBuffer0 = stringWriter0.getBuffer();
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(stringBuffer0);
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      PriorityQueue<Option> priorityQueue0 = new PriorityQueue<Option>();
      textHelpAppendable0.setIndent(0);
      Option option0 = mock(Option.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(option0).getDescription();
      doReturn((String) null).when(option0).getLongOpt();
      doReturn((String) null).when(option0).getOpt();
      doReturn((String) null).when(option0).getSince();
      doReturn((Object) null).when(option0).getType();
      doReturn(false).when(option0).hasArg();
      doReturn(false).when(option0).isDeprecated();
      doReturn(false).when(option0).isRequired();
      priorityQueue0.add(option0);
      PriorityQueue<Option> priorityQueue1 = new PriorityQueue<Option>(priorityQueue0);
      priorityQueue1.spliterator();
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) priorityQueue1);
      // Undeclared exception!
      try { 
        textHelpAppendable0.adjustTableFormat(tableDefinition0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      int int0 = (-248);
      textHelpAppendable0.setIndent((-248));
      textHelpAppendable0.appendList(true, (Collection<CharSequence>) null);
      String string0 = "[T9z9(ak;0tAA/ ";
      TextStyle textStyle0 = TextStyle.DEFAULT;
      textStyle0.pad(false, "[T9z9(ak;0tAA/ ");
      textStyle0.toString();
      textHelpAppendable0.printWrapped("[T9z9(ak;0tAA/ ", textStyle0);
      Vector<TextStyle> vector0 = new Vector<TextStyle>();
      // Undeclared exception!
      try { 
        textHelpAppendable0.writeColumnQueues((List<Queue<String>>) null, vector0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      String string0 = "Insensitive";
      LinkedList<TextStyle> linkedList0 = new LinkedList<TextStyle>();
      ArrayList<String> arrayList0 = new ArrayList<String>();
      Comparator<Object> comparator0 = (Comparator<Object>) mock(Comparator.class, new ViolatedAssumptionAnswer());
      arrayList0.add("Insensitive");
      linkedList0.removeFirstOccurrence(textHelpAppendable0);
      TreeSet<List<String>> treeSet0 = new TreeSet<List<String>>(comparator0);
      TableDefinition tableDefinition0 = TableDefinition.from("Insensitive", linkedList0, arrayList0, treeSet0);
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendTable(tableDefinition0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 0, Size: 0
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      Function.identity();
      Vector<Option> vector0 = new Vector<Option>();
      Function<Object, Iterable<Option>> function0 = (Function<Object, Iterable<Option>>) mock(Function.class, new ViolatedAssumptionAnswer());
      weirdOptionFormat0.compose((Function<? super String, ? extends Iterable<Option>>) function0);
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) vector0);
      LinkedList<TextStyle> linkedList0 = new LinkedList<TextStyle>();
      ArrayList<String> arrayList0 = new ArrayList<String>();
      UnaryOperator<Option> unaryOperator0 = UnaryOperator.identity();
      Option option0 = mock(Option.class, new ViolatedAssumptionAnswer());
      arrayList0.add("n-,_c~[G$");
      unaryOperator0.apply(option0);
      arrayList0.add("n*}!t'AeuKS");
      vector0.replaceAll(unaryOperator0);
      Comparator<List<String>> comparator0 = (Comparator<List<String>>) mock(Comparator.class, new ViolatedAssumptionAnswer());
      TreeSet<List<String>> treeSet0 = new TreeSet<List<String>>(comparator0);
      TableDefinition.from(" %s. %s", linkedList0, arrayList0, treeSet0);
      textHelpAppendable0.appendTable(tableDefinition0);
      TextHelpAppendable textHelpAppendable1 = TextHelpAppendable.systemOut();
      textHelpAppendable1.appendTitle("n-,_c~[G$");
      textHelpAppendable1.appendParagraph("n-,_c~[G$");
      textHelpAppendable0.getLeftPad();
      textHelpAppendable0.setMaxWidth((-2));
      textHelpAppendable1.appendTable(tableDefinition0);
      // Undeclared exception!
      try { 
        textHelpAppendable0.makeColumnQueues(arrayList0, linkedList0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 0, Size: 0
         //
         verifyException("java.util.LinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      String string0 = "org.apache.commons.io.filefilter.SizeFileFilter";
      MockFile mockFile0 = new MockFile("", "org.apache.commons.io.filefilter.SizeFileFilter");
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(mockFile0);
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(mockPrintWriter0);
      textHelpAppendable0.setMaxWidth((-180));
      TextHelpAppendable.indexOfWrap("", 74, 7);
      textHelpAppendable0.appendTitle("");
      TextHelpAppendable textHelpAppendable1 = TextHelpAppendable.systemOut();
      textHelpAppendable1.getTextStyleBuilder();
      mockFile0.setReadable(true);
      mockPrintWriter0.print((double) 3);
      textHelpAppendable0.getLeftPad();
      Object[] objectArray0 = new Object[1];
      objectArray0[0] = (Object) mockPrintWriter0;
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendParagraphFormat("org.apache.commons.io.filefilter.SizeFileFilter", objectArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Width must be greater than 0
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      LongestCommonSubsequence longestCommonSubsequence0 = new LongestCommonSubsequence();
      char[] charArray0 = new char[4];
      charArray0[0] = 'u';
      charArray0[1] = 'x';
      charArray0[2] = 'i';
      charArray0[3] = 'S';
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      longestCommonSubsequence0.longestCommonSubsequence(charBuffer0, charBuffer0);
      TextHelpAppendable.indexOfWrap("uxiS", 9, 35);
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      PriorityQueue<Option> priorityQueue0 = new PriorityQueue<Option>();
      PriorityQueue<Option> priorityQueue1 = new PriorityQueue<Option>(priorityQueue0);
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) priorityQueue1);
      TableDefinition tableDefinition1 = textHelpAppendable0.adjustTableFormat(tableDefinition0);
      List<TextStyle> list0 = tableDefinition0.columnTextStyles();
      Stack<String> stack0 = new Stack<String>();
      PriorityQueue<List<String>> priorityQueue2 = new PriorityQueue<List<String>>(4160);
      TableDefinition.from("", list0, stack0, priorityQueue2);
      textHelpAppendable0.adjustTableFormat(tableDefinition1);
      TextStyle.Builder textStyle_Builder0 = textHelpAppendable0.getTextStyleBuilder();
      textHelpAppendable0.resize(textStyle_Builder0, 4160);
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      textHelpAppendable0.getIndent();
      TextStyle textStyle0 = TextStyle.DEFAULT;
      textStyle0.toString();
      textHelpAppendable0.printWrapped("", textStyle0);
      textHelpAppendable0.getLeftPad();
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      TextStyle.Alignment textStyle_Alignment0 = TextStyle.Alignment.CENTER;
      LinkedHashSet<CharSequence> linkedHashSet0 = new LinkedHashSet<CharSequence>();
      textHelpAppendable0.appendList(true, linkedHashSet0);
      textStyle_Builder0.setAlignment(textStyle_Alignment0);
      textHelpAppendable0.resize(textStyle_Builder0, 3);
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      LongestCommonSubsequence longestCommonSubsequence0 = new LongestCommonSubsequence();
      char[] charArray0 = new char[1];
      charArray0[0] = 'u';
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      CharBuffer charBuffer1 = CharBuffer.wrap((CharSequence) charBuffer0, 0, 0);
      longestCommonSubsequence0.longestCommonSubsequence(charBuffer1, charBuffer1);
      FilterHelpAppendable filterHelpAppendable0 = textHelpAppendable0.append((CharSequence) "");
      TextHelpAppendable textHelpAppendable1 = new TextHelpAppendable(filterHelpAppendable0);
      ArrayList<TextStyle> arrayList0 = new ArrayList<TextStyle>();
      ArrayList<TextStyle> arrayList1 = new ArrayList<TextStyle>(arrayList0);
      LinkedList<String> linkedList0 = new LinkedList<String>();
      TableDefinition tableDefinition0 = TableDefinition.from("level must be at least 1", arrayList1, linkedList0, (Iterable<List<String>>) null);
      TableDefinition tableDefinition1 = textHelpAppendable1.adjustTableFormat(tableDefinition0);
      // Undeclared exception!
      try { 
        textHelpAppendable1.appendTable(tableDefinition1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      textHelpAppendable0.setMaxWidth(1873);
      Charset charset0 = Charset.defaultCharset();
      byte[] byteArray0 = new byte[4];
      byteArray0[0] = (byte)20;
      byteArray0[1] = (byte) (-111);
      byteArray0[2] = (byte) (-32);
      byteArray0[3] = (byte)0;
      ByteBuffer byteBuffer0 = ByteBuffer.wrap(byteArray0);
      Vector<CharSequence> vector0 = new Vector<CharSequence>();
      textHelpAppendable0.appendList(true, vector0);
      byteBuffer0.putFloat(4754.142F);
      CharBuffer charBuffer0 = charset0.decode(byteBuffer0);
      textHelpAppendable0.appendTitle(charBuffer0);
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      boolean boolean0 = true;
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      textStyle_Builder0.setIndent((-303));
      textHelpAppendable0.resize(textStyle_Builder0, (-2127.892));
      double double0 = 3118.648423839282;
      String string0 = " %s. %s";
      // Undeclared exception!
      try { 
        textHelpAppendable0.printWrapped(" %s. %s", (TextStyle) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      StringWriter stringWriter0 = new StringWriter(0);
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(stringWriter0);
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      ArrayList<Option> arrayList0 = new ArrayList<Option>();
      TreeSet<Option> treeSet0 = new TreeSet<Option>(arrayList0);
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) treeSet0);
      TableDefinition tableDefinition1 = textHelpAppendable0.adjustTableFormat(tableDefinition0);
      textHelpAppendable0.adjustTableFormat(tableDefinition1);
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      // Undeclared exception!
      try { 
        textHelpAppendable0.resize((TextStyle.Builder) null, 0.0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      textHelpAppendable0.getMaxWidth();
      Object[] objectArray0 = new Object[6];
      objectArray0[0] = (Object) " ";
      objectArray0[1] = (Object) "E04-0dQNvV?^wYR+U";
      objectArray0[2] = (Object) " ";
      objectArray0[3] = (Object) textHelpAppendable0;
      objectArray0[4] = (Object) " ";
      objectArray0[5] = (Object) textHelpAppendable0;
      textHelpAppendable0.appendFormat("E04-0dQNvV?^wYR+U", objectArray0);
      // Undeclared exception!
      try { 
        textHelpAppendable0.printWrapped(" ", (TextStyle) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      // Undeclared exception!
      try { 
        textHelpAppendable0.adjustTableFormat((TableDefinition) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      TextStyle.Builder textStyle_Builder0 = textHelpAppendable0.getTextStyleBuilder();
      textHelpAppendable0.resize(textStyle_Builder0, 0.0);
      textHelpAppendable0.setIndent(2363);
  }

  @Test(timeout = 4000)
  public void test63()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      CharBuffer charBuffer0 = CharBuffer.allocate(1);
      textHelpAppendable0.appendTitle(charBuffer0);
      TextHelpAppendable textHelpAppendable1 = TextHelpAppendable.systemOut();
      textHelpAppendable0.getLeftPad();
      textHelpAppendable0.setMaxWidth(1);
      textHelpAppendable1.getLeftPad();
      textHelpAppendable1.setMaxWidth(74);
      // Undeclared exception!
      try { 
        TextHelpAppendable.indexOfWrap(charBuffer0, 0, 3);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Width must be greater than 0
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test64()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      Object[] objectArray0 = new Object[4];
      objectArray0[0] = (Object) textHelpAppendable0;
      objectArray0[1] = (Object) textHelpAppendable0;
      objectArray0[2] = (Object) textHelpAppendable0;
      objectArray0[3] = (Object) textHelpAppendable0;
      textHelpAppendable0.appendFormat("\"/p", objectArray0);
      TextStyle textStyle0 = TextStyle.DEFAULT;
      textHelpAppendable0.printWrapped("$`OY`", textStyle0);
      textStyle0.toString();
      textHelpAppendable0.setMaxWidth(2364);
      textHelpAppendable0.printWrapped("%s%n");
      textHelpAppendable0.appendHeader(Integer.MAX_VALUE, "$`OY`");
      Stack<Queue<String>> stack0 = new Stack<Queue<String>>();
      ArrayList<TextStyle> arrayList0 = new ArrayList<TextStyle>();
      textHelpAppendable0.writeColumnQueues(stack0, arrayList0);
      textHelpAppendable0.appendParagraph("$`OY`");
      textHelpAppendable0.setLeftPad(592);
      textHelpAppendable0.setLeftPad(Integer.MAX_VALUE);
      char[] charArray0 = new char[8];
      charArray0[0] = 'l';
      charArray0[1] = ',';
      charArray0[2] = '<';
      charArray0[3] = 'W';
      charArray0[4] = 'd';
      charArray0[5] = 'a';
      charArray0[6] = '1';
      charArray0[7] = '9';
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      // Undeclared exception!
      textHelpAppendable0.appendTitle(charBuffer0);
  }

  @Test(timeout = 4000)
  public void test65()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      textHelpAppendable0.setLeftPad((-2688));
      TextStyle textStyle0 = TextStyle.DEFAULT;
      textStyle0.toString();
      char[] charArray0 = new char[3];
      charArray0[0] = 'n';
      charArray0[1] = 'T';
      charArray0[2] = '`';
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      textStyle0.pad(false, charBuffer0);
      CharBuffer charBuffer1 = CharBuffer.wrap((CharSequence) "nT`");
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendHeader((-2688), charBuffer1);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // level must be at least 1
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test66()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      Object[] objectArray0 = new Object[0];
      textHelpAppendable0.appendFormat("qZjEo", objectArray0);
      textHelpAppendable0.setMaxWidth((-2374));
      textHelpAppendable0.appendHeader(74, (CharSequence) null);
      textHelpAppendable0.appendHeader(3105, (CharSequence) null);
      textHelpAppendable0.append((CharSequence) null);
      textHelpAppendable0.getMaxWidth();
  }

  @Test(timeout = 4000)
  public void test67()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      TextHelpAppendable textHelpAppendable1 = new TextHelpAppendable(textHelpAppendable0);
      String string0 = null;
      Vector<Queue<String>> vector0 = new Vector<Queue<String>>();
      TextStyle textStyle0 = TextStyle.DEFAULT;
      // Undeclared exception!
      try { 
        textHelpAppendable1.makeColumnQueue((CharSequence) null, textStyle0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test68()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      StringWriter stringWriter0 = new StringWriter();
      StringBuffer stringBuffer0 = stringWriter0.getBuffer();
      TextStyle textStyle0 = TextStyle.DEFAULT;
      textHelpAppendable0.makeColumnQueue(stringBuffer0, textStyle0);
  }

  @Test(timeout = 4000)
  public void test69()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      textHelpAppendable0.resize(textStyle_Builder0, 0.0);
  }

  @Test(timeout = 4000)
  public void test70()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      TextStyle.Builder textStyle_Builder0 = textHelpAppendable0.getTextStyleBuilder();
      textHelpAppendable0.resize(textStyle_Builder0, 0.0);
      // Undeclared exception!
      try { 
        textHelpAppendable0.printWrapped((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test71()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      textHelpAppendable0.printWrapped("*Sx'@UyC");
      textHelpAppendable0.setMaxWidth(14);
      textHelpAppendable0.setMaxWidth(0);
  }

  @Test(timeout = 4000)
  public void test72()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable((Appendable) null);
      TextStyle.Builder textStyle_Builder0 = textHelpAppendable0.getTextStyleBuilder();
      textHelpAppendable0.resize(textStyle_Builder0, 0.0);
  }

  @Test(timeout = 4000)
  public void test73()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      HashSet<Option> hashSet0 = new HashSet<Option>();
      ArrayList<Option> arrayList0 = new ArrayList<Option>(hashSet0);
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) arrayList0);
      textHelpAppendable0.appendTable(tableDefinition0);
  }

  @Test(timeout = 4000)
  public void test74()  throws Throwable  {
      CharBuffer charBuffer0 = CharBuffer.allocate(3556);
      TextHelpAppendable.indexOfWrap(charBuffer0, 5, 0);
  }

  @Test(timeout = 4000)
  public void test75()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      FilterHelpAppendable filterHelpAppendable0 = textHelpAppendable0.append('%');
      TextHelpAppendable textHelpAppendable1 = new TextHelpAppendable(filterHelpAppendable0);
      textHelpAppendable1.getMaxWidth();
  }

  @Test(timeout = 4000)
  public void test76()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      textHelpAppendable0.setMaxWidth((-251));
  }

  @Test(timeout = 4000)
  public void test77()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      HashSet<Option> hashSet0 = new HashSet<Option>();
      ArrayList<Option> arrayList0 = new ArrayList<Option>(hashSet0);
      Option option0 = mock(Option.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(option0).getDescription();
      doReturn((String) null).when(option0).getLongOpt();
      doReturn((String) null).when(option0).getOpt();
      doReturn((String) null).when(option0).getSince();
      doReturn((Object) null).when(option0).getType();
      doReturn(false).when(option0).hasArg();
      doReturn(false).when(option0).isDeprecated();
      doReturn(false).when(option0).isRequired();
      arrayList0.add(option0);
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) arrayList0);
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendTable(tableDefinition0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test78()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      FileSystemHandling.shouldAllThrowIOExceptions();
      textHelpAppendable0.getTextStyleBuilder();
      textHelpAppendable0.printWrapped("S^5%wA:v#d'");
      TextHelpAppendable textHelpAppendable1 = TextHelpAppendable.systemOut();
      textHelpAppendable1.append('\\');
      textHelpAppendable0.getTextStyleBuilder();
      textHelpAppendable1.getTextStyleBuilder();
  }

  @Test(timeout = 4000)
  public void test79()  throws Throwable  {
      MockFile mockFile0 = new MockFile("", "org.apache.commons.io.filefilter.SizeFileFilter");
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(mockFile0);
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(mockPrintWriter0);
      textHelpAppendable0.setMaxWidth(53);
      int int0 = TextHelpAppendable.DEFAULT_LEFT_PAD;
      textHelpAppendable0.appendTitle("");
      TextHelpAppendable textHelpAppendable1 = TextHelpAppendable.systemOut();
      textHelpAppendable0.appendHeader((-3957), "");
      textHelpAppendable1.getTextStyleBuilder();
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("D:\\University\\Semester 5 - Winter 2026\\EECS4313 - Software Engineering Testing\\Assignment 2\\EECS4313-Assignment2");
      FileSystemHandling.createFolder(evoSuiteFile0);
      mockFile0.setReadable(true);
      Integer integer0 = new Integer(7);
      ArrayList<Queue<String>> arrayList0 = new ArrayList<Queue<String>>();
      textHelpAppendable0.writeColumnQueues(arrayList0, (List<TextStyle>) null);
      Object[] objectArray0 = new Object[1];
      objectArray0[0] = (Object) mockPrintWriter0;
      textHelpAppendable0.appendParagraphFormat("org.apache.commons.io.filefilter.SizeFileFilter", objectArray0);
      TextHelpAppendable.systemOut();
      textHelpAppendable0.appendTitle("org.apache.commons.io.filefilter.SizeFileFilter");
      TextStyle textStyle0 = TextStyle.DEFAULT;
      textStyle0.toString();
      textHelpAppendable0.makeColumnQueue("org.apache.commons.io.filefilter.SizeFileFilter", textStyle0);
      textHelpAppendable1.getTextStyleBuilder();
      textHelpAppendable1.setMaxWidth((int) integer0);
      LinkedList<Queue<String>> linkedList0 = new LinkedList<Queue<String>>();
      // Undeclared exception!
      try { 
        linkedList0.remove();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.LinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test80()  throws Throwable  {
      byte[] byteArray0 = new byte[6];
      byteArray0[1] = (byte)48;
      byteArray0[2] = (byte)24;
      byteArray0[3] = (byte)8;
      byteArray0[4] = (byte) (-3);
      byteArray0[5] = (byte)7;
      FileSystemHandling.appendDataToFile((EvoSuiteFile) null, byteArray0);
      CharBuffer charBuffer0 = CharBuffer.allocate(1483);
      CharBuffer.allocate(1483);
      FileSystemHandling.createFolder((EvoSuiteFile) null);
      TextHelpAppendable.indexOfWrap(charBuffer0, 1483, 1483);
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      textHelpAppendable0.setLeftPad(1483);
      FilterHelpAppendable filterHelpAppendable0 = textHelpAppendable0.append((CharSequence) charBuffer0);
      textHelpAppendable0.getLeftPad();
      textHelpAppendable0.appendParagraph(charBuffer0);
      textHelpAppendable0.getLeftPad();
      textHelpAppendable0.getLeftPad();
      textHelpAppendable0.getTextStyleBuilder();
      Stack<TextStyle> stack0 = new Stack<TextStyle>();
      TreeSet<List<String>> treeSet0 = new TreeSet<List<String>>();
      LinkedHashSet<List<String>> linkedHashSet0 = new LinkedHashSet<List<String>>(treeSet0);
      TableDefinition tableDefinition0 = TableDefinition.from("Xx,_`J)9VM5Nl10CR", stack0, (List<String>) null, linkedHashSet0);
      TableDefinition tableDefinition1 = textHelpAppendable0.adjustTableFormat(tableDefinition0);
      Vector<String> vector0 = new Vector<String>(1, (-310));
      textHelpAppendable0.appendList(false, (Collection<CharSequence>) null);
      // Undeclared exception!
      try { 
        ((TextHelpAppendable) filterHelpAppendable0).appendTable(tableDefinition1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test81()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      FileSystemHandling.shouldAllThrowIOExceptions();
      LinkedList<TextStyle> linkedList1 = new LinkedList<TextStyle>();
      textHelpAppendable0.makeColumnQueues(linkedList0, linkedList1);
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      LinkedHashSet<Option> linkedHashSet0 = new LinkedHashSet<Option>();
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) linkedHashSet0);
      TableDefinition tableDefinition1 = textHelpAppendable0.adjustTableFormat(tableDefinition0);
      TreeSet<List<String>> treeSet0 = new TreeSet<List<String>>();
      TreeSet<List<String>> treeSet1 = new TreeSet<List<String>>((SortedSet<List<String>>) treeSet0);
      textHelpAppendable0.adjustTableFormat(tableDefinition0);
      textHelpAppendable0.appendTable(tableDefinition1);
      TextHelpAppendable textHelpAppendable1 = TextHelpAppendable.systemOut();
      textHelpAppendable1.appendTable(tableDefinition1);
      LinkedList<CharSequence> linkedList2 = new LinkedList<CharSequence>();
      linkedList2.add((CharSequence) "C{k^QUQH;Ho*w[F^pKt");
      textHelpAppendable1.appendList(true, linkedList2);
      textHelpAppendable0.appendTable(tableDefinition0);
  }

  @Test(timeout = 4000)
  public void test82()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      textHelpAppendable0.getMaxWidth();
      TextStyle textStyle0 = TextStyle.DEFAULT;
      textHelpAppendable0.printWrapped("I2qe:f'NI>Y`PQ:", textStyle0);
      textStyle0.pad(false, "I2qe:f'NI>Y`PQ:");
      ArrayList<CharSequence> arrayList0 = new ArrayList<CharSequence>();
      textHelpAppendable0.setLeftPad(Integer.MAX_VALUE);
      arrayList0.add((CharSequence) "I2qe:f'NI>Y`PQ:");
      TreeSet<String> treeSet0 = new TreeSet<String>();
      arrayList0.addAll((Collection<? extends CharSequence>) treeSet0);
      TextHelpAppendable.indexOfWrap("I2qe:f'NI>Y`PQ:", 1481, 7);
      textStyle0.toString();
      // Undeclared exception!
      textHelpAppendable0.appendList(false, arrayList0);
  }

  @Test(timeout = 4000)
  public void test83()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      TextStyle textStyle0 = TextStyle.DEFAULT;
      textHelpAppendable0.setLeftPad(Integer.MAX_VALUE);
      textStyle0.toString();
      textHelpAppendable0.getLeftPad();
      textHelpAppendable0.getTextStyleBuilder();
      textHelpAppendable0.getTextStyleBuilder();
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      Comparator<Object> comparator0 = (Comparator<Object>) mock(Comparator.class, new ViolatedAssumptionAnswer());
      PriorityQueue<Option> priorityQueue0 = new PriorityQueue<Option>(Integer.MAX_VALUE, comparator0);
  }

  @Test(timeout = 4000)
  public void test84()  throws Throwable  {
      StringWriter stringWriter0 = new StringWriter(35);
      int int0 = 1419;
      CharBuffer charBuffer0 = CharBuffer.allocate(1419);
      CharBuffer charBuffer1 = CharBuffer.wrap((CharSequence) charBuffer0);
      CharBuffer charBuffer2 = CharBuffer.wrap((CharSequence) charBuffer1, 0, 35);
      charBuffer2.get();
      stringWriter0.append((CharSequence) charBuffer2);
      StringBuffer stringBuffer0 = stringWriter0.getBuffer();
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(stringBuffer0);
      textHelpAppendable0.getMaxWidth();
      textHelpAppendable0.appendTitle(charBuffer1);
      textHelpAppendable0.setMaxWidth(35);
      textHelpAppendable0.setIndent(74);
      char[] charArray0 = new char[8];
      charArray0[0] = '\u0000';
      charArray0[1] = '\u0000';
      charArray0[2] = '\u0000';
      charArray0[3] = '\u0000';
      charArray0[4] = '\u0000';
      charArray0[5] = '\u0000';
      stringWriter0.write(charArray0);
      charArray0[6] = '\u0000';
      charArray0[7] = 'A';
      stringWriter0.write(charArray0);
      TextHelpAppendable.indexOfWrap(stringBuffer0, 1419, 74);
      // Undeclared exception!
      try { 
        TextHelpAppendable.indexOfWrap(stringBuffer0, 0, 0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Width must be greater than 0
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test85()  throws Throwable  {
      char[] charArray0 = new char[0];
      File file0 = MockFile.createTempFile("Width must be greater than 0", "HYC'h[");
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream(file0, false);
      Charset charset0 = Charset.defaultCharset();
      CharsetEncoder charsetEncoder0 = charset0.newEncoder();
      OutputStreamWriter outputStreamWriter0 = new OutputStreamWriter(mockFileOutputStream0, charsetEncoder0);
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(outputStreamWriter0);
      textHelpAppendable0.appendHeader(764, "HYC'h[");
      ByteArrayOutputStream byteArrayOutputStream0 = new ByteArrayOutputStream(254);
      ObjectOutputStream objectOutputStream0 = new ObjectOutputStream(byteArrayOutputStream0);
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(objectOutputStream0);
      PrintWriter printWriter0 = mockPrintWriter0.append('A');
      TextHelpAppendable textHelpAppendable1 = new TextHelpAppendable(printWriter0);
      Locale locale0 = Locale.ITALY;
      Set<String> set0 = locale0.getUnicodeLocaleAttributes();
      Vector<CharSequence> vector0 = new Vector<CharSequence>(set0);
      textHelpAppendable1.appendList(true, vector0);
      // Undeclared exception!
      try { 
        CharBuffer.wrap(charArray0, 764, 2466);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.CharBuffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test86()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      textHelpAppendable0.setLeftPad((-2688));
      TextStyle textStyle0 = TextStyle.DEFAULT;
      textStyle0.toString();
      char[] charArray0 = new char[3];
      charArray0[0] = 'a';
      charArray0[1] = 'T';
      charArray0[2] = 'T';
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      textStyle0.pad(false, charBuffer0);
      CharBuffer charBuffer1 = CharBuffer.wrap((CharSequence) "aTT");
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendHeader((-2688), charBuffer1);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // level must be at least 1
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test87()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      CharBuffer charBuffer0 = CharBuffer.allocate(1);
      charBuffer0.mark();
      TextHelpAppendable textHelpAppendable1 = TextHelpAppendable.systemOut();
      textHelpAppendable0.appendParagraph(charBuffer0);
      Stack<Option> stack0 = new Stack<Option>();
      LinkedHashSet<Option> linkedHashSet0 = new LinkedHashSet<Option>(stack0);
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) linkedHashSet0);
      textHelpAppendable0.appendTable(tableDefinition0);
      TextStyle.Builder textStyle_Builder0 = textHelpAppendable0.getTextStyleBuilder();
      textHelpAppendable0.resize(textStyle_Builder0, (-1.0));
      Stack<String> stack1 = new Stack<String>();
      String string0 = "%s%n";
      stack1.add("%s%n");
      Consumer<Object> consumer0 = (Consumer<Object>) mock(Consumer.class, new ViolatedAssumptionAnswer());
      textHelpAppendable1.getIndent();
      textHelpAppendable1.getMaxWidth();
      ArrayList<TextStyle> arrayList0 = new ArrayList<TextStyle>();
      // Undeclared exception!
      try { 
        textHelpAppendable1.makeColumnQueues(stack1, arrayList0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 0, Size: 0
         //
         verifyException("java.util.ArrayList", e);
      }
  }
}
