/*
 * This file was automatically generated by EvoSuite
 * Thu Mar 12 22:16:18 GMT 2026
 */

package org.apache.commons.cli;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.lang.reflect.Array;
import java.time.chrono.HijrahEra;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import java.util.Properties;
import java.util.function.Consumer;
import java.util.function.Supplier;
import org.apache.commons.cli.CommandLine;
import org.apache.commons.cli.Option;
import org.apache.commons.cli.OptionGroup;
import org.apache.commons.text.TextStringBuilder;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CommandLine_ESTest extends CommandLine_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test000()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String[] stringArray0 = commandLine0.getOptionValues("-twE'CT&b");
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test001()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine.Builder commandLine_Builder1 = commandLine_Builder0.setDeprecatedHandler((Consumer<Option>) null);
      CommandLine commandLine0 = commandLine_Builder1.get();
      assertNotNull(commandLine0);
  }

  @Test(timeout = 4000)
  public void test002()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option("F", true, "F");
      commandLine0.addOption(option0);
      boolean boolean0 = commandLine0.hasOption("F");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test003()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      OptionGroup optionGroup0 = new OptionGroup();
      LinkedList<HijrahEra>[] linkedListArray0 = commandLine0.getParsedOptionValues(optionGroup0, (LinkedList<HijrahEra>[]) null);
      assertNull(linkedListArray0);
  }

  @Test(timeout = 4000)
  public void test004()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      Integer[] integerArray0 = new Integer[0];
      Integer[] integerArray1 = commandLine0.getParsedOptionValues(optionGroup0, integerArray0);
      assertEquals(0, integerArray1.length);
  }

  @Test(timeout = 4000)
  public void test005()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      Object[] objectArray0 = new Object[3];
      Supplier<Object[]> supplier0 = (Supplier<Object[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(objectArray0).when(supplier0).get();
      Object[] objectArray1 = commandLine0.getParsedOptionValues(optionGroup0, supplier0);
      assertEquals(3, objectArray1.length);
  }

  @Test(timeout = 4000)
  public void test006()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      String[] stringArray0 = new String[0];
      Supplier<Object[]> supplier0 = (Supplier<Object[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(stringArray0).when(supplier0).get();
      Object[] objectArray0 = commandLine0.getParsedOptionValues(optionGroup0, supplier0);
      assertSame(stringArray0, objectArray0);
  }

  @Test(timeout = 4000)
  public void test007()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Object[] objectArray0 = commandLine0.getParsedOptionValues((Option) null, (Object[]) null);
      assertNull(objectArray0);
  }

  @Test(timeout = 4000)
  public void test008()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option("suffixes", "suffixes");
      String[] stringArray0 = new String[0];
      String[] stringArray1 = commandLine0.getParsedOptionValues(option0, stringArray0);
      assertEquals(0, stringArray1.length);
  }

  @Test(timeout = 4000)
  public void test009()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option option0 = new Option((String) null, "");
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option[] optionArray0 = new Option[0];
      Supplier<Option[]> supplier0 = (Supplier<Option[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(optionArray0).when(supplier0).get();
      Option[] optionArray1 = commandLine0.getParsedOptionValues(option0, supplier0);
      assertSame(optionArray0, optionArray1);
  }

  @Test(timeout = 4000)
  public void test010()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Class<Object>[] classArray0 = commandLine0.getParsedOptionValues("KZx!U!86", (Class<Object>[]) null);
      assertNull(classArray0);
  }

  @Test(timeout = 4000)
  public void test011()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Integer[] integerArray0 = new Integer[0];
      Integer[] integerArray1 = commandLine0.getParsedOptionValues("", integerArray0);
      assertEquals(0, integerArray1.length);
  }

  @Test(timeout = 4000)
  public void test012()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Object[] objectArray0 = new Object[5];
      Supplier<Object[]> supplier0 = (Supplier<Object[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(objectArray0).when(supplier0).get();
      Object[] objectArray1 = commandLine0.getParsedOptionValues("GT<<?B01`B^OC^:", supplier0);
      assertSame(objectArray0, objectArray1);
  }

  @Test(timeout = 4000)
  public void test013()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      LinkedList<String>[] linkedListArray0 = (LinkedList<String>[]) Array.newInstance(LinkedList.class, 0);
      Supplier<LinkedList<String>[]> supplier0 = (Supplier<LinkedList<String>[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(linkedListArray0).when(supplier0).get();
      LinkedList<String>[] linkedListArray1 = commandLine0.getParsedOptionValues("", supplier0);
      assertEquals(0, linkedListArray1.length);
  }

  @Test(timeout = 4000)
  public void test014()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      String[] stringArray0 = commandLine0.getParsedOptionValues('p', (String[]) null);
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test015()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      HijrahEra[] hijrahEraArray0 = new HijrahEra[0];
      HijrahEra[] hijrahEraArray1 = commandLine0.getParsedOptionValues('q', hijrahEraArray0);
      assertSame(hijrahEraArray0, hijrahEraArray1);
  }

  @Test(timeout = 4000)
  public void test016()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Class<String>[] classArray0 = commandLine0.getParsedOptionValues('g', (Supplier<Class<String>[]>) null);
      assertNull(classArray0);
  }

  @Test(timeout = 4000)
  public void test017()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Integer[] integerArray0 = new Integer[0];
      Supplier<Integer[]> supplier0 = (Supplier<Integer[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(integerArray0).when(supplier0).get();
      Integer[] integerArray1 = commandLine0.getParsedOptionValues('t', supplier0);
      assertSame(integerArray1, integerArray0);
  }

  @Test(timeout = 4000)
  public void test018()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      OptionGroup optionGroup0 = new OptionGroup();
      String string0 = commandLine0.getParsedOptionValue(optionGroup0, (String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test019()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option("A", "A");
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      LinkedList<Object> linkedList1 = commandLine0.getParsedOptionValue(option0, linkedList0);
      assertSame(linkedList0, linkedList1);
  }

  @Test(timeout = 4000)
  public void test020()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Supplier<Object> supplier0 = (Supplier<Object>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(supplier0).get();
      Object object0 = commandLine0.getParsedOptionValue((String) null, supplier0);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test021()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getParsedOptionValue("`F", (String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test022()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Supplier<HijrahEra> supplier0 = (Supplier<HijrahEra>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(supplier0).get();
      commandLine0.getParsedOptionValue('0', supplier0);
  }

  @Test(timeout = 4000)
  public void test023()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Integer integer0 = commandLine0.getParsedOptionValue('/', (Integer) null);
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test024()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option option0 = new Option("dC", (String) null);
      CommandLine commandLine0 = commandLine_Builder0.get();
      commandLine_Builder0.addOption(option0);
      Option[] optionArray0 = commandLine0.getOptions();
      assertEquals(1, optionArray0.length);
  }

  @Test(timeout = 4000)
  public void test025()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      TextStringBuilder textStringBuilder0 = new TextStringBuilder();
      textStringBuilder0.insert(0, (long) (-2));
      String string0 = commandLine0.getOptionValue((OptionGroup) null, (Supplier<String>) textStringBuilder0);
      assertEquals("-2", string0);
  }

  @Test(timeout = 4000)
  public void test026()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      TextStringBuilder textStringBuilder0 = new TextStringBuilder();
      String string0 = commandLine0.getOptionValue(optionGroup0, (Supplier<String>) textStringBuilder0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test027()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      OptionGroup optionGroup0 = new OptionGroup();
      String string0 = commandLine0.getOptionValue(optionGroup0, (String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test028()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      String string0 = commandLine0.getOptionValue((OptionGroup) null, "");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test029()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option option0 = new Option("n", "Z", true, "j\"yN_-/,KF<6U");
      CommandLine commandLine0 = commandLine_Builder0.get();
      String string0 = commandLine0.getOptionValue(option0, (Supplier<String>) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test030()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option("F", "F", true, "F");
      TextStringBuilder textStringBuilder0 = new TextStringBuilder("H=SM4n:b$zk.@UL");
      String string0 = commandLine0.getOptionValue(option0, (Supplier<String>) textStringBuilder0);
      assertEquals("H=SM4n:b$zk.@UL", string0);
  }

  @Test(timeout = 4000)
  public void test031()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option option0 = new Option((String) null, false, (String) null);
      String string0 = commandLine0.getOptionValue(option0, "\"Q$<N");
      assertEquals("\"Q$<N", string0);
  }

  @Test(timeout = 4000)
  public void test032()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getOptionValue((Option) null, "");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test033()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      char[] charArray0 = new char[2];
      TextStringBuilder textStringBuilder0 = TextStringBuilder.wrap(charArray0);
      String string0 = commandLine0.getOptionValue((String) null, (Supplier<String>) textStringBuilder0);
      assertEquals("\u0000\u0000", string0);
  }

  @Test(timeout = 4000)
  public void test034()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      TextStringBuilder textStringBuilder0 = new TextStringBuilder((-91));
      String string0 = commandLine0.getOptionValue("", (Supplier<String>) textStringBuilder0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test035()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      String[] stringArray0 = new String[2];
      String string0 = commandLine0.getOptionValue(stringArray0[0], (String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test036()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getOptionValue("[4iZ}A)K7;OJ", "");
      assertNotNull(string0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test037()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getOptionValue('', (Supplier<String>) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test038()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      StringBuilder stringBuilder0 = new StringBuilder();
      StringBuilder stringBuilder1 = stringBuilder0.append("&;rtt5s$#z^");
      TextStringBuilder textStringBuilder0 = new TextStringBuilder(stringBuilder1);
      String string0 = commandLine0.getOptionValue('Y', (Supplier<String>) textStringBuilder0);
      assertEquals("&;rtt5s$#z^", string0);
  }

  @Test(timeout = 4000)
  public void test039()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      String string0 = commandLine0.getOptionValue('b', (String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test040()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getOptionValue('?', "");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test041()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option option0 = new Option((String) null, true, "*Y");
      commandLine_Builder0.addOption(option0);
      CommandLine commandLine0 = commandLine_Builder0.get();
      int int0 = commandLine0.getOptionCount(option0);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test042()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option("F", "F", true, "F");
      commandLine0.addOption(option0);
      int int0 = commandLine0.getOptionCount("F");
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test043()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine.Builder commandLine_Builder1 = commandLine_Builder0.addArg("");
      CommandLine commandLine0 = commandLine_Builder1.get();
      String[] stringArray0 = commandLine0.getArgs();
      assertEquals(1, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test044()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine.Builder commandLine_Builder1 = commandLine_Builder0.addArg("args");
      CommandLine commandLine0 = commandLine_Builder1.get();
      List<String> list0 = commandLine0.getArgList();
      assertTrue(list0.contains("args"));
  }

  @Test(timeout = 4000)
  public void test045()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option.Builder option_Builder0 = Option.builder();
      // Undeclared exception!
      try { 
        commandLine0.getParsedOptionValue((OptionGroup) null, (Supplier<Option>) option_Builder0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Either opt or longOpt must be specified
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test046()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option option0 = new Option("dC", (String) null);
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option.Builder option_Builder0 = Option.builder((String) null);
      try { 
        commandLine0.getParsedOptionValue(option0, (Supplier<Option>) option_Builder0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // org.evosuite.runtime.mock.java.lang.MockThrowable: Either opt or longOpt must be specified
         //
         verifyException("org.apache.commons.cli.ParseException", e);
      }
  }

  @Test(timeout = 4000)
  public void test047()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option.Builder option_Builder0 = Option.builder();
      // Undeclared exception!
      try { 
        commandLine0.getParsedOptionValue((Option) null, (Supplier<Option>) option_Builder0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Either opt or longOpt must be specified
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test048()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option.Builder option_Builder0 = Option.builder();
      // Undeclared exception!
      try { 
        commandLine0.getParsedOptionValue((String) null, (Supplier<Option>) option_Builder0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Either opt or longOpt must be specified
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test049()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option option0 = new Option("dC", (String) null);
      CommandLine commandLine0 = commandLine_Builder0.get();
      commandLine_Builder0.addOption(option0);
      // Undeclared exception!
      try { 
        commandLine0.getOptionProperties((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test050()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option option0 = new Option("wxjR", false, "o@RAN ?");
      CommandLine.Builder commandLine_Builder1 = commandLine_Builder0.addOption(option0);
      CommandLine commandLine0 = commandLine_Builder1.get();
      boolean boolean0 = commandLine0.hasOption(option0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test051()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.option("oWOpFCHNNkV0");
      Option option0 = option_Builder0.get();
      boolean boolean0 = commandLine0.hasOption(option0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test052()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      Supplier<Object[]> supplier0 = (Supplier<Object[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(supplier0).get();
      Object[] objectArray0 = commandLine0.getParsedOptionValues(optionGroup0, supplier0);
      assertNull(objectArray0);
  }

  @Test(timeout = 4000)
  public void test053()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Supplier<Object[]> supplier0 = (Supplier<Object[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(supplier0).get();
      Object[] objectArray0 = commandLine0.getParsedOptionValues((OptionGroup) null, supplier0);
      assertNull(objectArray0);
  }

  @Test(timeout = 4000)
  public void test054()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      HijrahEra[] hijrahEraArray0 = commandLine0.getParsedOptionValues((Option) null, (Supplier<HijrahEra[]>) null);
      assertNull(hijrahEraArray0);
  }

  @Test(timeout = 4000)
  public void test055()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option("SENSITIVE", "org.apache.commons.text.similarity.JaccardDistance", false, "org.apache.commons.text.similarity.JaccardDistance");
      Integer[] integerArray0 = new Integer[7];
      Supplier<Integer[]> supplier0 = (Supplier<Integer[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(integerArray0).when(supplier0).get();
      Integer[] integerArray1 = commandLine0.getParsedOptionValues(option0, supplier0);
      assertSame(integerArray1, integerArray0);
  }

  @Test(timeout = 4000)
  public void test056()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      Supplier<LinkedList<String>> supplier0 = (Supplier<LinkedList<String>>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(linkedList0).when(supplier0).get();
      LinkedList<String> linkedList1 = commandLine0.getParsedOptionValue(optionGroup0, supplier0);
      assertSame(linkedList0, linkedList1);
  }

  @Test(timeout = 4000)
  public void test057()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option("F", true, "F");
      OptionGroup optionGroup0 = new OptionGroup();
      optionGroup0.setSelected(option0);
      Class<HijrahEra> class0 = commandLine0.getParsedOptionValue(optionGroup0, (Supplier<Class<HijrahEra>>) null);
      assertNull(class0);
  }

  @Test(timeout = 4000)
  public void test058()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      TextStringBuilder textStringBuilder0 = new TextStringBuilder();
      String string0 = commandLine0.getParsedOptionValue((Option) null, (Supplier<String>) textStringBuilder0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test059()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option("SENSITIVE", "org.apache.commons.text.similarity.JaccardDistance", false, "org.apache.commons.text.similarity.JaccardDistance");
      Supplier<Object> supplier0 = (Supplier<Object>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(supplier0).get();
      Object object0 = commandLine0.getParsedOptionValue(option0, supplier0);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test060()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String[] stringArray0 = commandLine0.getOptionValues((OptionGroup) null);
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test061()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option option0 = new Option("true", "98jB6jh`yW", false, "true");
      OptionGroup optionGroup0 = new OptionGroup();
      optionGroup0.setSelected(option0);
      String[] stringArray0 = commandLine0.getOptionValues(optionGroup0);
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test062()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      String[] stringArray0 = commandLine0.getOptionValues(optionGroup0);
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test063()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String[] stringArray0 = commandLine0.getOptionValues((Option) null);
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test064()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option("F", "F", true, "F");
      String[] stringArray0 = commandLine0.getOptionValues(option0);
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test065()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      String string0 = commandLine0.getOptionValue(optionGroup0, (Supplier<String>) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test066()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option("A", "A");
      TextStringBuilder textStringBuilder0 = new TextStringBuilder((-613));
      String string0 = commandLine0.getOptionValue(option0, (Supplier<String>) textStringBuilder0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test067()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      int int0 = commandLine0.getOptionCount("'Hu!<F#");
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test068()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option[] optionArray0 = commandLine0.getParsedOptionValues((Option) null);
      assertNull(optionArray0);
  }

  @Test(timeout = 4000)
  public void test069()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Supplier<LinkedList<String>[]> supplier0 = (Supplier<LinkedList<String>[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(supplier0).get();
      LinkedList<String>[] linkedListArray0 = commandLine0.getParsedOptionValues("", supplier0);
      assertNull(linkedListArray0);
  }

  @Test(timeout = 4000)
  public void test070()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      TextStringBuilder textStringBuilder0 = new TextStringBuilder((-3296));
      String string0 = commandLine0.getParsedOptionValue("2", (Supplier<String>) textStringBuilder0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test071()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option("?", "[yl=kpn~||xtky&", true, "!mc");
      int int0 = commandLine0.getOptionCount(option0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test072()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getOptionValue("C");
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test073()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option[] optionArray0 = commandLine0.getParsedOptionValues("");
      assertNull(optionArray0);
  }

  @Test(timeout = 4000)
  public void test074()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option("A", "A");
      Object object0 = commandLine0.getParsedOptionValue(option0);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test075()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getOptionValue(":+@?i(n!yaN1a@T", (Supplier<String>) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test076()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      boolean boolean0 = commandLine0.hasOption("");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test077()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option((String) null, (String) null, true, (String) null);
      String string0 = commandLine0.getOptionValue(option0);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test078()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = commandLine0.getParsedOptionValue((Option) null, (Option) null);
      assertNull(option0);
  }

  @Test(timeout = 4000)
  public void test079()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      String string0 = commandLine0.getParsedOptionValue("DP-.N");
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test080()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      OptionGroup optionGroup0 = new OptionGroup();
      boolean boolean0 = commandLine0.hasOption(optionGroup0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test081()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      boolean boolean0 = commandLine0.hasOption((OptionGroup) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test082()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option option0 = new Option("args", "args", false, "args");
      commandLine_Builder0.addOption(option0);
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option.Builder option_Builder0 = Option.builder("args");
      Option.Builder option_Builder1 = option_Builder0.longOpt("args");
      Option.Builder option_Builder2 = option_Builder1.deprecated();
      Option option1 = option_Builder2.get();
      boolean boolean0 = commandLine0.hasOption(option1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test083()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option("F", true, "F");
      commandLine0.addOption(option0);
      OptionGroup optionGroup0 = new OptionGroup();
      optionGroup0.setSelected(option0);
      boolean boolean0 = commandLine0.hasOption(optionGroup0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test084()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option option0 = new Option("args", "args", false, "args");
      CommandLine.Builder commandLine_Builder1 = commandLine_Builder0.addOption(option0);
      CommandLine commandLine0 = commandLine_Builder1.get();
      Option.Builder option_Builder0 = Option.builder("args");
      Option.Builder option_Builder1 = option_Builder0.longOpt("args");
      option_Builder1.deprecated();
      Option option1 = option_Builder1.get();
      Integer[] integerArray0 = new Integer[2];
      Integer[] integerArray1 = commandLine0.getParsedOptionValues(option1, integerArray0);
      assertSame(integerArray1, integerArray0);
  }

  @Test(timeout = 4000)
  public void test085()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      OptionGroup optionGroup0 = new OptionGroup();
      String string0 = commandLine0.getOptionValue(optionGroup0);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test086()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      String string0 = commandLine0.getOptionValue((OptionGroup) null, "org.apache.commons.cli.CommandLine$Builder");
      assertEquals("org.apache.commons.cli.CommandLine$Builder", string0);
  }

  @Test(timeout = 4000)
  public void test087()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option("F", true, "F");
      commandLine0.addOption(option0);
      OptionGroup optionGroup0 = new OptionGroup();
      optionGroup0.setSelected(option0);
      commandLine0.getParsedOptionValue(optionGroup0);
  }

  @Test(timeout = 4000)
  public void test088()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      commandLine0.addOption((Option) null);
  }

  @Test(timeout = 4000)
  public void test089()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      commandLine0.addArg("U");
  }

  @Test(timeout = 4000)
  public void test090()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      commandLine0.addArg((String) null);
  }

  @Test(timeout = 4000)
  public void test091()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option option0 = new Option("dC", (String) null);
      commandLine_Builder0.addOption(option0);
      CommandLine commandLine0 = commandLine_Builder0.get();
      Properties properties0 = commandLine0.getOptionProperties(option0);
      assertEquals(0, properties0.size());
  }

  @Test(timeout = 4000)
  public void test092()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine.Builder commandLine_Builder1 = commandLine_Builder0.addOption((Option) null);
      assertSame(commandLine_Builder0, commandLine_Builder1);
  }

  @Test(timeout = 4000)
  public void test093()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine.Builder commandLine_Builder1 = commandLine_Builder0.addArg((String) null);
      assertSame(commandLine_Builder1, commandLine_Builder0);
  }

  @Test(timeout = 4000)
  public void test094()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      String[] stringArray0 = commandLine0.getArgs();
      assertEquals(0, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test095()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String[] stringArray0 = commandLine0.getOptionValues('\'');
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test096()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getOptionValue("str1", "str1");
      assertEquals("str1", string0);
  }

  @Test(timeout = 4000)
  public void test097()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option[] optionArray0 = commandLine0.getOptions();
      assertEquals(0, optionArray0.length);
  }

  @Test(timeout = 4000)
  public void test098()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Object[] objectArray0 = new Object[6];
      Object[] objectArray1 = commandLine0.getParsedOptionValues('.', objectArray0);
      assertSame(objectArray1, objectArray0);
  }

  @Test(timeout = 4000)
  public void test099()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      List<String> list0 = commandLine0.getArgList();
      OptionGroup optionGroup0 = new OptionGroup();
      LinkedList linkedList0 = (LinkedList)commandLine0.getParsedOptionValue(optionGroup0, (Object) list0);
      assertEquals(0, linkedList0.size());
  }

  @Test(timeout = 4000)
  public void test100()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option((String) null, "org.apache.commons.cli.CommandLine$Builder", false, "str1");
      String string0 = commandLine0.getOptionValue(option0, (String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test101()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      boolean boolean0 = commandLine0.hasOption('b');
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test102()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Object object0 = commandLine0.getOptionObject('?');
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test103()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      String[] stringArray0 = new String[4];
      String[] stringArray1 = commandLine0.getParsedOptionValues((OptionGroup) null, stringArray0);
      assertSame(stringArray1, stringArray0);
  }

  @Test(timeout = 4000)
  public void test104()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Properties properties0 = commandLine0.getOptionProperties("");
      assertTrue(properties0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test105()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      String[] stringArray0 = new String[3];
      Supplier<String[]> supplier0 = (Supplier<String[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(stringArray0).when(supplier0).get();
      String[] stringArray1 = commandLine0.getParsedOptionValues('f', supplier0);
      assertSame(stringArray0, stringArray1);
  }

  @Test(timeout = 4000)
  public void test106()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Object object0 = commandLine0.getOptionObject((String) null);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test107()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Integer[] integerArray0 = commandLine0.getParsedOptionValues('$');
      assertNull(integerArray0);
  }

  @Test(timeout = 4000)
  public void test108()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      OptionGroup optionGroup0 = new OptionGroup();
      Integer[] integerArray0 = commandLine0.getParsedOptionValues(optionGroup0);
      assertNull(integerArray0);
  }

  @Test(timeout = 4000)
  public void test109()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      TextStringBuilder textStringBuilder0 = new TextStringBuilder((-590));
      String string0 = commandLine0.getOptionValue('B', (Supplier<String>) textStringBuilder0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test110()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      LinkedList<Object> linkedList1 = commandLine0.getParsedOptionValue('`', linkedList0);
      assertFalse(linkedList1.contains('`'));
  }

  @Test(timeout = 4000)
  public void test111()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getOptionValue('<', "str1");
      assertEquals("str1", string0);
  }

  @Test(timeout = 4000)
  public void test112()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      LinkedList<String>[] linkedListArray0 = (LinkedList<String>[]) Array.newInstance(LinkedList.class, 8);
      LinkedList<String>[] linkedListArray1 = commandLine0.getParsedOptionValues("F", linkedListArray0);
      assertEquals(8, linkedListArray1.length);
  }

  @Test(timeout = 4000)
  public void test113()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Iterator<Option> iterator0 = commandLine0.iterator();
      assertNotNull(iterator0);
  }

  @Test(timeout = 4000)
  public void test114()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      TextStringBuilder textStringBuilder0 = new TextStringBuilder((-590));
      String string0 = commandLine0.getParsedOptionValue('f', (Supplier<String>) textStringBuilder0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test115()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      Option option0 = new Option((String) null, "org.apache.commons.cli.CommandLine$Builder", false, "str1");
      optionGroup0.setSelected(option0);
      Object[] objectArray0 = commandLine0.getParsedOptionValues(optionGroup0, (Supplier<Object[]>) null);
      assertNull(objectArray0);
  }

  @Test(timeout = 4000)
  public void test116()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      int int0 = commandLine0.getOptionCount('z');
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test117()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      HijrahEra hijrahEra0 = HijrahEra.AH;
      HijrahEra hijrahEra1 = commandLine0.getParsedOptionValue("options", hijrahEra0);
      assertEquals(HijrahEra.AH, hijrahEra1);
  }

  @Test(timeout = 4000)
  public void test118()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Integer integer0 = commandLine0.getParsedOptionValue('*');
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test119()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getOptionValue('c');
      assertNull(string0);
  }
}
