/*
 * This file was automatically generated by EvoSuite
 * Fri Mar 13 23:48:47 GMT 2026
 */

package org.apache.commons.cli;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.lang.reflect.Array;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import java.util.Locale;
import java.util.Properties;
import java.util.function.Consumer;
import java.util.function.Supplier;
import org.apache.commons.cli.CommandLine;
import org.apache.commons.cli.DeprecatedAttributes;
import org.apache.commons.cli.Option;
import org.apache.commons.cli.OptionGroup;
import org.apache.commons.text.TextStringBuilder;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CommandLine_ESTest extends CommandLine_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test000()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine.Builder commandLine_Builder1 = commandLine_Builder0.setDeprecatedHandler((Consumer<Option>) null);
      CommandLine commandLine0 = commandLine_Builder1.get();
      assertNotNull(commandLine0);
  }

  @Test(timeout = 4000)
  public void test001()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option option0 = new Option("@", "hJ~N_xa|L_}Fhw9", true, "@");
      commandLine_Builder0.addOption(option0);
      CommandLine commandLine0 = commandLine_Builder0.get();
      boolean boolean0 = commandLine0.hasOption("@");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test002()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      LinkedList<String>[] linkedListArray0 = commandLine0.getParsedOptionValues(optionGroup0, (LinkedList<String>[]) null);
      assertNull(linkedListArray0);
  }

  @Test(timeout = 4000)
  public void test003()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      LinkedList<Object>[] linkedListArray0 = (LinkedList<Object>[]) Array.newInstance(LinkedList.class, 0);
      LinkedList<Object>[] linkedListArray1 = commandLine0.getParsedOptionValues(optionGroup0, linkedListArray0);
      assertSame(linkedListArray1, linkedListArray0);
  }

  @Test(timeout = 4000)
  public void test004()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      OptionGroup optionGroup0 = new OptionGroup();
      Object[] objectArray0 = new Object[0];
      Supplier<Object[]> supplier0 = (Supplier<Object[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(objectArray0).when(supplier0).get();
      Object[] objectArray1 = commandLine0.getParsedOptionValues(optionGroup0, supplier0);
      assertEquals(0, objectArray1.length);
  }

  @Test(timeout = 4000)
  public void test005()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option((String) null, (String) null, true, "");
      Locale.FilteringMode[] locale_FilteringModeArray0 = commandLine0.getParsedOptionValues(option0, (Locale.FilteringMode[]) null);
      assertNull(locale_FilteringModeArray0);
  }

  @Test(timeout = 4000)
  public void test006()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option((String) null, "-fTYjL ^/BBaLF\"^");
      String[] stringArray0 = new String[0];
      String[] stringArray1 = commandLine0.getParsedOptionValues(option0, stringArray0);
      assertSame(stringArray0, stringArray1);
  }

  @Test(timeout = 4000)
  public void test007()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Supplier<LinkedList<Object>[]> supplier0 = (Supplier<LinkedList<Object>[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(supplier0).get();
      LinkedList<Object>[] linkedListArray0 = commandLine0.getParsedOptionValues((Option) null, supplier0);
      assertNull(linkedListArray0);
  }

  @Test(timeout = 4000)
  public void test008()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option("args", "args");
      Option[] optionArray0 = new Option[0];
      Supplier<Option[]> supplier0 = (Supplier<Option[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(optionArray0).when(supplier0).get();
      Option[] optionArray1 = commandLine0.getParsedOptionValues(option0, supplier0);
      assertSame(optionArray0, optionArray1);
  }

  @Test(timeout = 4000)
  public void test009()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      LinkedList<Option>[] linkedListArray0 = (LinkedList<Option>[]) Array.newInstance(LinkedList.class, 7);
      LinkedList<Option>[] linkedListArray1 = commandLine0.getParsedOptionValues("E&/BbARvv0R", linkedListArray0);
      assertSame(linkedListArray1, linkedListArray0);
  }

  @Test(timeout = 4000)
  public void test010()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Supplier<String[]> supplier0 = (Supplier<String[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(supplier0).get();
      String[] stringArray0 = commandLine0.getParsedOptionValues("", supplier0);
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test011()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Object[] objectArray0 = commandLine0.getParsedOptionValues('B', (Object[]) null);
      assertNull(objectArray0);
  }

  @Test(timeout = 4000)
  public void test012()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Object[] objectArray0 = new Object[9];
      Object[] objectArray1 = commandLine0.getParsedOptionValues('_', objectArray0);
      assertSame(objectArray1, objectArray0);
  }

  @Test(timeout = 4000)
  public void test013()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Supplier<Option[]> supplier0 = (Supplier<Option[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn((Option[]) null).when(supplier0).get();
      Option[] optionArray0 = commandLine0.getParsedOptionValues('R', supplier0);
      assertNull(optionArray0);
  }

  @Test(timeout = 4000)
  public void test014()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option[] optionArray0 = new Option[1];
      Supplier<Option[]> supplier0 = (Supplier<Option[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(optionArray0).when(supplier0).get();
      Option[] optionArray1 = commandLine0.getParsedOptionValues('R', supplier0);
      assertSame(optionArray0, optionArray1);
  }

  @Test(timeout = 4000)
  public void test015()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      OptionGroup optionGroup0 = new OptionGroup();
      Integer integer0 = commandLine0.getParsedOptionValue(optionGroup0, (Integer) null);
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test016()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option("Q", "INSENSITIVE", false, "2D");
      Supplier<Object> supplier0 = (Supplier<Object>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(option0.UNLIMITED_VALUES).when(supplier0).get();
      Object object0 = commandLine0.getParsedOptionValue(option0, supplier0);
      assertEquals((-2), object0);
  }

  @Test(timeout = 4000)
  public void test017()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option option0 = new Option("fileFilters", "Coh]gk0=ljkg");
      CommandLine commandLine0 = commandLine_Builder0.get();
      Object object0 = commandLine0.getParsedOptionValue(option0, (Object) null);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test018()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Class<String> class0 = String.class;
      Supplier<Class<String>> supplier0 = (Supplier<Class<String>>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(class0).when(supplier0).get();
      Class<String> class1 = commandLine0.getParsedOptionValue("[ARG...]", supplier0);
      assertFalse(class1.isPrimitive());
  }

  @Test(timeout = 4000)
  public void test019()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      LinkedList<Option> linkedList0 = commandLine0.getParsedOptionValue((String) null, (LinkedList<Option>) null);
      assertNull(linkedList0);
  }

  @Test(timeout = 4000)
  public void test020()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
      Supplier<LinkedList<Integer>> supplier0 = (Supplier<LinkedList<Integer>>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(linkedList0).when(supplier0).get();
      LinkedList<Integer> linkedList1 = commandLine0.getParsedOptionValue('o', supplier0);
      assertSame(linkedList1, linkedList0);
  }

  @Test(timeout = 4000)
  public void test021()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option("gT", "Exception found converting ", true, "");
      LinkedList<String> linkedList0 = commandLine0.getParsedOptionValue(option0, (Supplier<LinkedList<String>>) null);
      Object object0 = commandLine0.getParsedOptionValue('m', (Object) linkedList0);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test022()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option((String) null, "");
      commandLine0.addOption(option0);
      Option[] optionArray0 = commandLine0.getOptions();
      assertEquals(1, optionArray0.length);
  }

  @Test(timeout = 4000)
  public void test023()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      TextStringBuilder textStringBuilder0 = new TextStringBuilder("args");
      String string0 = commandLine0.getOptionValue(optionGroup0, (Supplier<String>) textStringBuilder0);
      assertEquals("args", string0);
  }

  @Test(timeout = 4000)
  public void test024()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      TextStringBuilder textStringBuilder0 = new TextStringBuilder(0);
      String string0 = commandLine0.getOptionValue(optionGroup0, (Supplier<String>) textStringBuilder0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test025()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      String string0 = commandLine0.getOptionValue(optionGroup0, (String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test026()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      String string0 = commandLine0.getOptionValue(optionGroup0, "");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test027()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option("args", "args");
      String string0 = commandLine0.getOptionValue(option0, (Supplier<String>) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test028()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      TextStringBuilder textStringBuilder0 = new TextStringBuilder("K");
      Option option0 = new Option("K", "gT", false, (String) null);
      String string0 = commandLine0.getOptionValue(option0, (Supplier<String>) textStringBuilder0);
      assertEquals("K", string0);
  }

  @Test(timeout = 4000)
  public void test029()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option((String) null, (String) null, false, "");
      String string0 = commandLine0.getOptionValue(option0, (String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test030()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      String string0 = commandLine0.getOptionValue((Option) null, "org.apache.commons.cli.CommandLine$Builder");
      assertEquals("org.apache.commons.cli.CommandLine$Builder", string0);
  }

  @Test(timeout = 4000)
  public void test031()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      TextStringBuilder textStringBuilder0 = new TextStringBuilder("true");
      String string0 = commandLine0.getOptionValue("s*7\"ms{:", (Supplier<String>) textStringBuilder0);
      assertEquals("true", string0);
  }

  @Test(timeout = 4000)
  public void test032()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      TextStringBuilder textStringBuilder0 = new TextStringBuilder();
      String string0 = commandLine0.getOptionValue((String) null, (Supplier<String>) textStringBuilder0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test033()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getOptionValue("pattern", "pattern");
      assertEquals("pattern", string0);
  }

  @Test(timeout = 4000)
  public void test034()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getOptionValue("Ocv", "");
      assertEquals("", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test035()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getOptionValue('h', (Supplier<String>) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test036()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      char[] charArray0 = new char[3];
      TextStringBuilder textStringBuilder0 = TextStringBuilder.wrap(charArray0);
      String string0 = commandLine0.getOptionValue('h', (Supplier<String>) textStringBuilder0);
      assertEquals("\u0000\u0000\u0000", string0);
  }

  @Test(timeout = 4000)
  public void test037()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      String string0 = commandLine0.getOptionValue('5', (String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test038()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getOptionValue('#', "");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test039()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option option0 = new Option("0", "0", true, "0");
      CommandLine.Builder commandLine_Builder1 = commandLine_Builder0.addOption(option0);
      CommandLine commandLine0 = commandLine_Builder1.get();
      int int0 = commandLine0.getOptionCount(option0);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test040()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option option0 = new Option("fileFilters", "fileFilters", true, "fileFilters");
      CommandLine.Builder commandLine_Builder1 = commandLine_Builder0.addOption(option0);
      CommandLine commandLine0 = commandLine_Builder1.get();
      int int0 = commandLine0.getOptionCount("fileFilters");
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test041()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine.Builder commandLine_Builder1 = commandLine_Builder0.addArg("");
      CommandLine commandLine0 = commandLine_Builder1.get();
      List<String> list0 = commandLine0.getArgList();
      assertTrue(list0.contains(""));
  }

  @Test(timeout = 4000)
  public void test042()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option.Builder option_Builder0 = Option.builder();
      // Undeclared exception!
      try { 
        commandLine0.getParsedOptionValue("?]Q~+H0YD;Tb", (Supplier<Option>) option_Builder0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Either opt or longOpt must be specified
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test043()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option.Builder option_Builder0 = Option.builder();
      // Undeclared exception!
      try { 
        commandLine0.getParsedOptionValue('0', (Supplier<Option>) option_Builder0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Either opt or longOpt must be specified
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test044()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option option0 = new Option((String) null, "Exception found converting ");
      CommandLine.Builder commandLine_Builder1 = commandLine_Builder0.addOption(option0);
      CommandLine commandLine0 = commandLine_Builder1.get();
      // Undeclared exception!
      try { 
        commandLine0.getOptionProperties((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test045()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option option0 = new Option((String) null, false, (String) null);
      commandLine_Builder0.addOption(option0);
      boolean boolean0 = commandLine0.hasOption(option0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test046()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      boolean boolean0 = commandLine0.hasOption((Option) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test047()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      Integer[] integerArray0 = new Integer[3];
      Supplier<Integer[]> supplier0 = (Supplier<Integer[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(integerArray0).when(supplier0).get();
      Integer[] integerArray1 = commandLine0.getParsedOptionValues(optionGroup0, supplier0);
      assertEquals(3, integerArray1.length);
  }

  @Test(timeout = 4000)
  public void test048()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Supplier<String[]> supplier0 = (Supplier<String[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(supplier0).get();
      String[] stringArray0 = commandLine0.getParsedOptionValues((OptionGroup) null, supplier0);
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test049()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      LinkedList<Object>[] linkedListArray0 = (LinkedList<Object>[]) Array.newInstance(LinkedList.class, 1);
      Supplier<LinkedList<Object>[]> supplier0 = (Supplier<LinkedList<Object>[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(linkedListArray0).when(supplier0).get();
      LinkedList<Object>[] linkedListArray1 = commandLine0.getParsedOptionValues((Option) null, supplier0);
      assertSame(linkedListArray0, linkedListArray1);
  }

  @Test(timeout = 4000)
  public void test050()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option.Builder option_Builder0 = Option.builder();
      OptionGroup optionGroup0 = new OptionGroup();
      // Undeclared exception!
      try { 
        commandLine0.getParsedOptionValue(optionGroup0, (Supplier<Option>) option_Builder0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Either opt or longOpt must be specified
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test051()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      OptionGroup optionGroup0 = new OptionGroup();
      Option option0 = new Option((String) null, "", true, "");
      char[] charArray0 = new char[2];
      optionGroup0.setSelected(option0);
      TextStringBuilder textStringBuilder0 = TextStringBuilder.wrap(charArray0);
      String string0 = commandLine0.getParsedOptionValue(optionGroup0, (Supplier<String>) textStringBuilder0);
      assertEquals("\u0000\u0000", string0);
  }

  @Test(timeout = 4000)
  public void test052()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option.Builder option_Builder0 = Option.builder();
      // Undeclared exception!
      try { 
        commandLine0.getParsedOptionValue((Option) null, (Supplier<Option>) option_Builder0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Either opt or longOpt must be specified
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test053()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option((String) null, (String) null, true, "");
      Option.Builder option_Builder0 = Option.builder();
      try { 
        commandLine0.getParsedOptionValue(option0, (Supplier<Option>) option_Builder0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // org.evosuite.runtime.mock.java.lang.MockThrowable: Either opt or longOpt must be specified
         //
         verifyException("org.apache.commons.cli.ParseException", e);
      }
  }

  @Test(timeout = 4000)
  public void test054()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      String[] stringArray0 = commandLine0.getOptionValues((OptionGroup) null);
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test055()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option option0 = new Option("fileFilters", "fileFilters", true, "fileFilters");
      CommandLine commandLine0 = commandLine_Builder0.get();
      OptionGroup optionGroup0 = new OptionGroup();
      optionGroup0.setSelected(option0);
      String[] stringArray0 = commandLine0.getOptionValues(optionGroup0);
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test056()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      String[] stringArray0 = commandLine0.getOptionValues(optionGroup0);
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test057()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      String[] stringArray0 = commandLine0.getOptionValues((Option) null);
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test058()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option("gT", "Exception found converting ", true, "");
      String[] stringArray0 = commandLine0.getOptionValues(option0);
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test059()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option("gT", "Exception found converting ", true, "");
      TextStringBuilder textStringBuilder0 = new TextStringBuilder();
      String string0 = commandLine0.getOptionValue(option0, (Supplier<String>) textStringBuilder0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test060()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      int int0 = commandLine0.getOptionCount("K");
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test061()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      String string0 = commandLine0.getOptionValue(optionGroup0);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test062()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option[] optionArray0 = new Option[2];
      Supplier<Option[]> supplier0 = (Supplier<Option[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(optionArray0).when(supplier0).get();
      Option[] optionArray1 = commandLine0.getParsedOptionValues("org.apache.commons.cli.CommandLine", supplier0);
      assertSame(optionArray1, optionArray0);
  }

  @Test(timeout = 4000)
  public void test063()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Supplier<Class<String>> supplier0 = (Supplier<Class<String>>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(supplier0).get();
      Class<String> class0 = commandLine0.getParsedOptionValue("[ARG...]", supplier0);
      assertNull(class0);
  }

  @Test(timeout = 4000)
  public void test064()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option("suffixes", false, (String) null);
      int int0 = commandLine0.getOptionCount(option0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test065()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getOptionValue("fileFilters");
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test066()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option[] optionArray0 = commandLine0.getParsedOptionValues("TSM4/]sT.U  ");
      assertNull(optionArray0);
  }

  @Test(timeout = 4000)
  public void test067()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String[] stringArray0 = commandLine0.getOptionValues("args");
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test068()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getOptionValue("ytG9QGc:OP&wzL[", (Supplier<String>) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test069()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Object object0 = commandLine0.getOptionObject((String) null);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test070()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      boolean boolean0 = commandLine0.hasOption("nTX\"f7kUiyDhk*Z38t");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test071()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option option0 = new Option((String) null, "", true, "");
      Option option1 = commandLine0.getParsedOptionValue(option0, option0);
      assertNull(option1.getValue());
  }

  @Test(timeout = 4000)
  public void test072()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Object object0 = commandLine0.getParsedOptionValue(" to desired type: ");
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test073()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Object[] objectArray0 = commandLine0.getParsedOptionValues((String) null, (Object[]) null);
      assertNull(objectArray0);
  }

  @Test(timeout = 4000)
  public void test074()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option option0 = new Option("fileFilters", "fileFilters", true, "fileFilters");
      CommandLine.Builder commandLine_Builder1 = commandLine_Builder0.addOption(option0);
      CommandLine commandLine0 = commandLine_Builder1.get();
      Properties properties0 = commandLine0.getOptionProperties(option0);
      assertTrue(properties0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test075()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      boolean boolean0 = commandLine0.hasOption(optionGroup0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test076()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      boolean boolean0 = commandLine0.hasOption((OptionGroup) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test077()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      Option option0 = new Option("args", "args");
      optionGroup0.setSelected(option0);
      commandLine0.addOption(option0);
      boolean boolean0 = commandLine0.hasOption(optionGroup0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test078()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.longOpt("!R{QKE$0");
      DeprecatedAttributes.Builder deprecatedAttributes_Builder0 = DeprecatedAttributes.builder();
      DeprecatedAttributes deprecatedAttributes0 = deprecatedAttributes_Builder0.get();
      Option.Builder option_Builder1 = option_Builder0.deprecated(deprecatedAttributes0);
      Option option0 = option_Builder1.get();
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      commandLine_Builder0.addOption(option0);
      String string0 = commandLine0.getOptionValue(option0);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test079()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      Option option0 = new Option("args", (String) null);
      optionGroup0.setSelected(option0);
      Supplier<Option[]> supplier0 = (Supplier<Option[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(supplier0).get();
      Option[] optionArray0 = commandLine0.getParsedOptionValues(optionGroup0, supplier0);
      assertNull(optionArray0);
  }

  @Test(timeout = 4000)
  public void test080()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      Class<Object>[] classArray0 = commandLine0.getParsedOptionValues(optionGroup0);
      assertNull(classArray0);
  }

  @Test(timeout = 4000)
  public void test081()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.longOpt("!R{QKE$0");
      Option option0 = option_Builder1.get();
      String[] stringArray0 = commandLine0.getParsedOptionValues(option0);
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test082()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      Option option0 = new Option("args", "args");
      optionGroup0.setSelected(option0);
      String string0 = commandLine0.getParsedOptionValue(optionGroup0, "[ Option args :: args :: class java.lang.String ]");
      assertEquals("[ Option args :: args :: class java.lang.String ]", string0);
  }

  @Test(timeout = 4000)
  public void test083()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Supplier<Locale.FilteringMode> supplier0 = (Supplier<Locale.FilteringMode>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(supplier0).get();
      commandLine0.getParsedOptionValue((OptionGroup) null, supplier0);
  }

  @Test(timeout = 4000)
  public void test084()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option option0 = new Option("args", " to desired type: ");
      CommandLine commandLine0 = commandLine_Builder0.get();
      commandLine0.getParsedOptionValue(option0);
  }

  @Test(timeout = 4000)
  public void test085()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      Option option0 = new Option("args", "args");
      optionGroup0.setSelected(option0);
      String string0 = commandLine0.getOptionValue(optionGroup0, "[ Option args :: args :: class java.lang.String ]");
      assertEquals("[ Option args :: args :: class java.lang.String ]", string0);
  }

  @Test(timeout = 4000)
  public void test086()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      String string0 = commandLine0.getOptionValue((OptionGroup) null, (Supplier<String>) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test087()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      commandLine0.addOption((Option) null);
  }

  @Test(timeout = 4000)
  public void test088()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      commandLine0.addArg("org.apache.commons.text.lookup.XmlEncoderStringLookup");
      String[] stringArray0 = commandLine0.getArgs();
      assertEquals(1, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test089()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      commandLine0.addArg((String) null);
  }

  @Test(timeout = 4000)
  public void test090()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine.Builder commandLine_Builder1 = commandLine_Builder0.addOption((Option) null);
      assertSame(commandLine_Builder1, commandLine_Builder0);
  }

  @Test(timeout = 4000)
  public void test091()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine.Builder commandLine_Builder1 = commandLine_Builder0.addArg((String) null);
      assertSame(commandLine_Builder0, commandLine_Builder1);
  }

  @Test(timeout = 4000)
  public void test092()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String[] stringArray0 = commandLine0.getArgs();
      String[] stringArray1 = commandLine0.getParsedOptionValues("Q", stringArray0);
      assertEquals(0, stringArray1.length);
  }

  @Test(timeout = 4000)
  public void test093()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      OptionGroup optionGroup0 = new OptionGroup();
      Integer integer0 = commandLine0.getParsedOptionValue(optionGroup0);
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test094()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getOptionValue("org.apache.commons.cli.CommandLine$Builder", (String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test095()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option[] optionArray0 = commandLine0.getOptions();
      assertEquals(0, optionArray0.length);
  }

  @Test(timeout = 4000)
  public void test096()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      List<String> list0 = commandLine0.getArgList();
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test097()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.longOpt("!R{QKE$0");
      Option option0 = option_Builder0.get();
      String string0 = commandLine0.getOptionValue(option0, "");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test098()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      boolean boolean0 = commandLine0.hasOption('.');
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test099()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Object[] objectArray0 = new Object[5];
      Object[] objectArray1 = commandLine0.getParsedOptionValues((OptionGroup) null, objectArray0);
      assertSame(objectArray0, objectArray1);
  }

  @Test(timeout = 4000)
  public void test100()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Properties properties0 = commandLine0.getOptionProperties("0");
      assertEquals(0, properties0.size());
  }

  @Test(timeout = 4000)
  public void test101()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Object object0 = commandLine0.getOptionObject('1');
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test102()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String[] stringArray0 = commandLine0.getParsedOptionValues('R');
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test103()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String[] stringArray0 = commandLine0.getOptionValues('q');
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test104()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      TextStringBuilder textStringBuilder0 = new TextStringBuilder(0);
      String string0 = commandLine0.getOptionValue('-', (Supplier<String>) textStringBuilder0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test105()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getParsedOptionValue('K', "org.apache.commons.text.lookup.XmlEncoderStringLookup");
      assertEquals("org.apache.commons.text.lookup.XmlEncoderStringLookup", string0);
  }

  @Test(timeout = 4000)
  public void test106()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getOptionValue('q', "org.apache.commons.text.lookup.XmlEncoderStringLookup");
      assertEquals("org.apache.commons.text.lookup.XmlEncoderStringLookup", string0);
  }

  @Test(timeout = 4000)
  public void test107()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option[] optionArray0 = new Option[0];
      Option[] optionArray1 = commandLine0.getParsedOptionValues('4', optionArray0);
      assertSame(optionArray0, optionArray1);
  }

  @Test(timeout = 4000)
  public void test108()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Iterator<Option> iterator0 = commandLine0.iterator();
      assertNotNull(iterator0);
  }

  @Test(timeout = 4000)
  public void test109()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Supplier<Object> supplier0 = (Supplier<Object>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn((Integer) null).when(supplier0).get();
      Object object0 = commandLine0.getParsedOptionValue('-', supplier0);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test110()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Object[] objectArray0 = new Object[0];
      Supplier<Object[]> supplier0 = (Supplier<Object[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(objectArray0).when(supplier0).get();
      Object[] objectArray1 = commandLine0.getParsedOptionValues('-', supplier0);
      assertSame(objectArray1, objectArray0);
  }

  @Test(timeout = 4000)
  public void test111()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      int int0 = commandLine0.getOptionCount('1');
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test112()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Integer integer0 = new Integer(2076);
      Integer integer1 = commandLine0.getParsedOptionValue("options", integer0);
      assertEquals(2076, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test113()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      LinkedList<Locale.FilteringMode> linkedList0 = commandLine0.getParsedOptionValue('m');
      assertNull(linkedList0);
  }

  @Test(timeout = 4000)
  public void test114()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      String[] stringArray0 = new String[1];
      String[] stringArray1 = commandLine0.getParsedOptionValues((Option) null, stringArray0);
      assertEquals(1, stringArray1.length);
  }

  @Test(timeout = 4000)
  public void test115()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      String string0 = commandLine0.getOptionValue('X');
      assertNull(string0);
  }
}
