/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Fri Mar 13 23:52:33 GMT 2026
 */

package org.apache.commons.cli;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class PatternOptionBuilder_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.apache.commons.cli.PatternOptionBuilder"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "Cp1252"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\huynh\\AppData\\Local\\Temp\\"); 
    java.lang.System.setProperty("user.country", "US"); 
    java.lang.System.setProperty("user.dir", "D:\\University\\Semester 5 - Winter 2026\\EECS4313 - Software Engineering Testing\\Assignment 2\\EECS4313-Assignment2"); 
    java.lang.System.setProperty("user.home", "C:\\Users\\huynh"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "huynh"); 
    java.lang.System.setProperty("user.timezone", "America/New_York"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(PatternOptionBuilder_ESTest_scaffolding.class.getClassLoader() ,
      "org.apache.commons.cli.PatternOptionBuilder",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper",
      "org.apache.commons.cli.Options",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper$3",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper$2",
      "net.bytebuddy.description.ModifierReviewable",
      "net.bytebuddy.description.ModifierReviewable$OfAbstraction",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper$4",
      "net.bytebuddy.description.ModifierReviewable$OfByteCodeElement",
      "net.bytebuddy.implementation.Implementation",
      "net.bytebuddy.description.ByteCodeElement",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper$1",
      "net.bytebuddy.description.ModifierReviewable$OfEnumeration",
      "net.bytebuddy.dynamic.scaffold.InstrumentedType$Prepareable",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance",
      "org.apache.commons.cli.Converter",
      "net.bytebuddy.implementation.attribute.MethodAttributeAppender",
      "org.apache.commons.cli.OptionValidator",
      "net.bytebuddy.description.DeclaredByType",
      "net.bytebuddy.build.Plugin",
      "org.apache.commons.cli.Option",
      "net.bytebuddy.description.annotation.AnnotationSource",
      "net.bytebuddy.implementation.EqualsMethod",
      "org.apache.commons.cli.DeprecatedAttributes",
      "net.bytebuddy.description.NamedElement$WithRuntimeName",
      "net.bytebuddy.description.TypeVariableSource",
      "org.apache.commons.cli.Option$Builder",
      "net.bytebuddy.implementation.attribute.MethodAttributeAppender$Factory",
      "net.bytebuddy.description.ModifierReviewable$ForTypeDefinition",
      "org.apache.commons.cli.TypeHandler",
      "net.bytebuddy.description.NamedElement$WithDescriptor",
      "net.bytebuddy.matcher.ElementMatcher",
      "org.apache.commons.cli.AlreadySelectedException",
      "net.bytebuddy.build.Plugin$Factory",
      "org.apache.commons.cli.ParseException",
      "net.bytebuddy.description.type.TypeDefinition",
      "net.bytebuddy.implementation.HashCodeMethod",
      "org.apache.commons.cli.OptionGroup",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin",
      "net.bytebuddy.description.type.TypeDescription",
      "net.bytebuddy.description.NamedElement"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(PatternOptionBuilder_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.apache.commons.cli.PatternOptionBuilder",
      "org.apache.commons.cli.Converter",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper",
      "org.apache.commons.cli.Options",
      "org.apache.commons.cli.Option",
      "org.apache.commons.cli.Option$Builder",
      "org.apache.commons.cli.OptionValidator",
      "org.apache.commons.cli.TypeHandler"
    );
  }
}
