/*
 * This file was automatically generated by EvoSuite
 * Fri Mar 13 23:52:33 GMT 2026
 */

package org.apache.commons.cli;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.cli.Options;
import org.apache.commons.cli.PatternOptionBuilder;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PatternOptionBuilder_ESTest extends PatternOptionBuilder_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      // Undeclared exception!
      try { 
        PatternOptionBuilder.parsePattern((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.PatternOptionBuilder", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      boolean boolean0 = PatternOptionBuilder.isValueCode('!');
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      boolean boolean0 = PatternOptionBuilder.isValueCode('+');
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      boolean boolean0 = PatternOptionBuilder.isValueCode(':');
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      boolean boolean0 = PatternOptionBuilder.isValueCode('*');
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      boolean boolean0 = PatternOptionBuilder.isValueCode('/');
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      boolean boolean0 = PatternOptionBuilder.isValueCode('@');
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      boolean boolean0 = PatternOptionBuilder.isValueCode('.');
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      boolean boolean0 = PatternOptionBuilder.isValueCode('#');
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Class<?> class0 = PatternOptionBuilder.getValueType('%');
      assertNotNull(class0);
      assertEquals("class java.lang.Number", class0.toString());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Class<?> class0 = PatternOptionBuilder.getValueType('/');
      assertEquals("class java.net.URL", class0.toString());
      assertNotNull(class0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Class<?> class0 = PatternOptionBuilder.getValueType('+');
      assertEquals("class java.lang.Class", class0.toString());
      assertNotNull(class0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Class<?> class0 = PatternOptionBuilder.getValueType('=');
      assertNull(class0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Class<?> class0 = PatternOptionBuilder.getValueType('@');
      assertNotNull(class0);
      assertEquals("class java.lang.Object", class0.toString());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Class<?> class0 = PatternOptionBuilder.getValueType(':');
      assertNotNull(class0);
      assertEquals("class java.lang.String", class0.toString());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Class<?> class0 = PatternOptionBuilder.getValueType('*');
      assertTrue(class0.isArray());
      assertNotNull(class0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Class<?> class0 = PatternOptionBuilder.getValueType('#');
      assertNotNull(class0);
      assertEquals("class java.util.Date", class0.toString());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Options options0 = PatternOptionBuilder.parsePattern("vEX9#");
      assertNotNull(options0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Options options0 = PatternOptionBuilder.parsePattern("Not yet implemented");
      assertNotNull(options0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Options options0 = PatternOptionBuilder.parsePattern("!/");
      assertNotNull(options0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      boolean boolean0 = PatternOptionBuilder.isValueCode('>');
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      boolean boolean0 = PatternOptionBuilder.isValueCode('<');
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      boolean boolean0 = PatternOptionBuilder.isValueCode('%');
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Class<?> class0 = PatternOptionBuilder.getValueType('>');
      assertNotNull(class0);
      assertEquals("class java.io.File", class0.toString());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Class<?> class0 = PatternOptionBuilder.getValueType('<');
      assertEquals("class java.io.FileInputStream", class0.toString());
      assertNotNull(class0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      // Undeclared exception!
      try { 
        PatternOptionBuilder.parsePattern("OBVBa:^/k:");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Illegal option name '^'.
         //
         verifyException("org.apache.commons.cli.OptionValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Class class0 = (Class)PatternOptionBuilder.getValueClass('%');
      assertEquals(1025, class0.getModifiers());
      assertNotNull(class0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Class<Short> class0 = PatternOptionBuilder.unsupported();
      assertNotNull(class0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Object object0 = PatternOptionBuilder.getValueClass('P');
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      PatternOptionBuilder patternOptionBuilder0 = new PatternOptionBuilder();
  }
}
