/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 14 00:08:42 GMT 2026
 */

package org.apache.commons.cli;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.time.chrono.ThaiBuddhistEra;
import java.util.List;
import java.util.Stack;
import java.util.Vector;
import org.apache.commons.cli.MissingOptionException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MissingOptionException_ESTest extends MissingOptionException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Stack<Object> stack0 = new Stack<Object>();
      MissingOptionException missingOptionException0 = new MissingOptionException(stack0);
      stack0.add((Object) null);
      List list0 = missingOptionException0.getMissingOptions();
      assertFalse(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MissingOptionException missingOptionException0 = null;
      try {
        missingOptionException0 = new MissingOptionException((List) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.MissingOptionException", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MissingOptionException missingOptionException0 = new MissingOptionException("@Vm'8%");
      List list0 = missingOptionException0.getMissingOptions();
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Vector<ThaiBuddhistEra> vector0 = new Vector<ThaiBuddhistEra>();
      ThaiBuddhistEra thaiBuddhistEra0 = ThaiBuddhistEra.BEFORE_BE;
      vector0.add(thaiBuddhistEra0);
      MissingOptionException missingOptionException0 = new MissingOptionException(vector0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Vector<ThaiBuddhistEra> vector0 = new Vector<ThaiBuddhistEra>();
      MissingOptionException missingOptionException0 = new MissingOptionException(vector0);
      List list0 = missingOptionException0.getMissingOptions();
      assertTrue(list0.isEmpty());
  }
}
